### ISSUE TITLE
Character count bug related to dismissed content warnings

### ISSUE THREAD

**Issue by mkosler** [Vavassor/Tusky#102]
If I write text in a content warning, and then decide against using the content warning and uncheck it, the character counter still shows the text I dismissed counting against my maximum. It doesn't actually affect whether or not I can toot, because when I tested the word "Test" in the content warning I was able to make a post that went 4 characters beyond the maximum. So it seems to just be a visual bug.

**Comment by Vavassor** [comment]
Oh that makes sense. When you check/uncheck that option, all it does is show/hide the content warning text box, so those characters still exist in the background being counted. But it does a separate count when sending that only counts the content warning if it's checked. So just a case I missed.
