### ISSUE TITLE
Posted Images May Appear Rotated

### ISSUE THREAD

**Issue by Vavassor** [Vavassor/Tusky#106]
After posting a status with images, they are sometimes rotated 90 degrees counter-clockwise.

My first guess would be this could happen for images that are downsized. Since the whole image is being recreated at a smaller size, it seems like a likely stage where an unintended rotation could be introduced.

**Comment by connyduck** [comment]
I know this issue from my apps on Samsung devices. (Some?) Samsung devices do not rotate pictures taken with the camera but store the rotation in the EXIF-data which gets lost during resizing. The solution is to read the exif data and rotate the picture if needed.

**Comment by claiire** [comment]
I get this too occasionally
