### ISSUE TITLE
Icons should be dark gray instead of pure black  (light theme)

### ISSUE THREAD

**Issue by elioqoshi** [Vavassor/Tusky#112]
First off, great work you are doing!

I wanted to suggest to change the color of the icons from pitch black to dark gray, something like: #646464

It's a bit easier on the eyes, yet has enough contrast for accessbility :)

**Comment by wavebeem** [comment]
Material Design states the icons should be #000000 black with 54% opacity.

![image](https://cloud.githubusercontent.com/assets/176815/24839723/d99cbffa-1d14-11e7-807b-29c62214f372.png)

**Comment by elioqoshi** [comment]
Yep, that would be ideal indeed. 54% is around the same as the value I proposed.

**Comment by Vavassor** [comment]
This was just done as of pull request #288 and merged in commit 90ed68d3169ac995caecf002a14721ee1f974b70.
