### ISSUE TITLE
Add visual effect before and when Toot is send

### ISSUE THREAD

**Issue by daycode** [Vavassor/Tusky#114]
A user posted on mastodon, when he press the Toot button, nothing appear (perhaps an instance error). So we should have a visual effect for error or success when send a Toot.

**Comment by theZacAttacks** [comment]
When there is an error I think a little pop-up appears letting the user know

**Comment by daycode** [comment]
Yeah, I forgot the error message, but I think we should have a spinner or a loading feedback for let the user know something is in progress and a success one. (when an instance have performance issue, a toot can take few seconds)

**Comment by theZacAttacks** [comment]
I'll look into trying to do this tomorrow.

**Comment by theZacAttacks** [comment]
Done and done! PR #121
