### ISSUE TITLE
Toot action buttons are too big

### ISSUE THREAD

**Issue by elioqoshi** [Vavassor/Tusky#117]
The action buttons on each toot are quite big. Making them around 60% of the current size should be ideal

What I propose:
![1](https://cloud.githubusercontent.com/assets/5436686/24841251/79c47462-1d80-11e7-807b-b4c461607474.jpg)

The original current one:
![2](https://cloud.githubusercontent.com/assets/5436686/24841253/834e2244-1d80-11e7-8d61-67e6cefe0948.jpg)

**Comment by daycode** [comment]
Did you make a PSD or something to have the new width value ? 🤔

**Comment by elioqoshi** [comment]
No, but it's exactly 70% of the original width, so if you know that, you can adapt it I guess :)

**Comment by Vavassor** [comment]
On my phone at least, the buttons are already not always easy to hit with my fingers. So I'd really rather not make them smaller. Unless, possibly, their effective touch area is larger than how they appear?

**Comment by alerque** [comment]
The icon size shouldn't limit the touchable area. The drawn icons are definitely cumbersomely large, but if you want to keep the active area wider than the icon that's fine.

**Comment by elioqoshi** [comment]
Yeah, the touch area could be definitely larger, maybe even as large as it is right now.

**Comment by charlag** [comment]
@connyduck do we have any plans on this? We could do poll in Masto but I think I'm pretty content with the current size

**Comment by charlag** [comment]
Okay, maybe if we don't change touch area it's fine, I could event do this

**Comment by elioqoshi** [comment]
Totally agree that touch area could stay the same

**Comment by connyduck** [comment]
Addressed in #445
