### ISSUE TITLE
Option to add content warning no longer appearing

### ISSUE THREAD

**Issue by asnider** [Vavassor/Tusky#118]
As stated in the title. It also appears to break CW when replying to a toot/thread that uses one.

Android 7.1.1

**Comment by jidhub** [comment]
This happens to me when replying to a toot.

**Comment by ntngrtltr** [comment]
Which version of the app are you using? If you buil it from source, which commit?
Related: #97

**Comment by asnider** [comment]
Version 1.1.0, installed from the Play Store.

**Comment by ntngrtltr** [comment]
Seems like it's not reproducible for me with my installation. My first thought was that something went wrong with the feature mentioned above, but it is not included in v1.1.0.
Did the CWs break with an update or out of the blue?

**Comment by daycode** [comment]
can't reproduce too, now we are in v1.1.4, do you have this bug again ? if not, can you close that issue ?

**Comment by asnider** [comment]
It's been resolved. Closing the issue.
