### ISSUE TITLE
Replying: parent toot review on swiping down

### ISSUE THREAD

**Issue by eidolies** [Vavassor/Tusky#119]
In the reply view, when composing a reply to a toot, swiping down the compose area and holding could show the content of the toot you're replying to by sliding it from above. Releasing would make it disappear so you can continue writing. 

Useful when you need to read the toot again to clarify your point or avoid neglecting details, especially useful with long toots.

**Comment by alerque** [comment]
I like the idea, but the UI sounds complex and unpredictable. Just putting the toot at the top of the screen and then the compose area would be enough. Scrolling up would get you a look at what your were replying to.

**Comment by theZacAttacks** [comment]
Would something (like this)[https://drive.google.com/open?id=1Ayo3DiMF9O-JJAGsJ1MbPHheHuQfjrlSRQ] be okay?

**Comment by eidolies** [comment]
I was more thinking of a way to see both at the same time, I like @alerque's scrolling up idea.
