### ISSUE TITLE
Submitting Tusky to other stores like Amazon Store

### ISSUE THREAD

**Issue by koyuawsmbrtn** [Vavassor/Tusky#120]
What about submitting Tusky to other Android-based stores like Aptoide and Amazon Store? I made a "mirror" (outdated version) from Tusky in Aptoide. I would publish it to the Amazon as well of course mentioning Vavassor. It would make the reach of the app a bit better, because users of "other phones" will have access too easily. Just a thought, maintainers can close this issue, when it's not relevant. Has anyone feedback for this? I'm really planning it to make it a bigger project. Like I said, there is just an outdated Aptoide version I published in my repo for transferring the app to the Amazon tablet of my brother. It's a bit hard to find out, when a new release comes out and this might delay it, when I do it alone, so I need a small reminder on Mastodon pushing the new update if it would come out. Tusky is still in alpha for me and alot of work must be done causing an enormous number of updates, but that's another thing.

**Comment by mltnhm** [comment]
Name-dropping F-Droid, quite popular for OSS apps.

**Comment by Vavassor** [comment]
@mltnhm I'd really like to be on F-Droid but a lot of work needs to be put in to replace Firebase entirely. I could get it on F-Droid sooner by splitting the build and having F-Droid's version use "pull" notifications like I used during Tusky's alpha. I just haven't taken the necessary steps there, yet.

**Comment by Vavassor** [comment]
I thought of Amazon, I hadn't actually heard of Aptoide until now. I should probably be the person to put them up? I'm going to wait until this update (1.1.1) is finished, though.

**Comment by klundry** [comment]
I wanted to say I would also like for it to be available on f-droid. Even without push notifications it would be good. I personally don't care about push notifications.

**Comment by koyuawsmbrtn** [comment]
But why not flagging the app on F-Droid with "Advertises other networks" and "Part of the source code isn't public"?

**Comment by mltnhm** [comment]
@Vavassor Aptoide is quite popular for piracy AFAIK.

**Comment by Vavassor** [comment]
It's now on the [Amazon appstore](https://www.amazon.com/products/gp/B06ZYXT88G/ref=mas_pm_tusky) and [F-Droid](https://f-droid.org/repository/browse/?fdid=com.keylesspalace.tusky), by the way.

**Comment by koyuawsmbrtn** [comment]
I saw, thanks. I guess, that issue can be closed.
