### ISSUE TITLE
Blank content - More detail in error message displayed to user 

### ISSUE THREAD

**Issue by redbarnnobrakes** [Vavassor/Tusky#125]
Interface should provide the user with a more detailed error message when the content is blank. This is even more important when new users are trying to figure out the 'Hide text behind warning' feature. It is not readily apparent that the user must also enter text in the "What's happening?" box as well as the "Content warning" box as shown in the attached screenshot.

Instead of

> The status failed to be sent

The user should be provided an error message similar to the one using a browser

> 422Validation failed: Text can't be blank

![image](https://cloud.githubusercontent.com/assets/14085766/24893697/fe53b95c-1e4a-11e7-912d-a51c17177e71.png)
![image](https://cloud.githubusercontent.com/assets/14085766/24893700/0326af20-1e4b-11e7-81b6-b512ec58ea15.png)

**Comment by Vavassor** [comment]
As of commit 84741c1f1bba2722754fd17a2141dbb1850076e9 all text fields that aren't allowed to be empty give the error message "This cannot be empty". So, this was fixed in the Tusky 1.1.3 release.
