### ISSUE TITLE
[Feature request] Allow to configure a proxy in Tusky

### ISSUE THREAD

**Issue by cjeanneret** [Vavassor/Tusky#130]
Hello,

It would be marvelous if user could configure a proxy in the application. For example, that feature would allow users to make connections through Tor, or other services like that.

Thank you for your time, and a big, big :+1: for Tusky as my preferred app for Mastodon :)

Cheers,

C.

**Comment by connyduck** [comment]
Proxy support was added in Tusky 1.5 :)
