### ISSUE TITLE
Connection to tuskynotifier.keylesspalace.com

### ISSUE THREAD

**Issue by bohwaz** [Vavassor/Tusky#132]
My Android firewall notifies me that Tusky tries to connect to that domain, what is that for? is it needed for anything?

**Comment by connyduck** [comment]
It is for pushmessages. Disable them in the settings and tusky should not connect to that server anymore.

**Comment by bohwaz** [comment]
Ah ok. Then if I understand the code correctly, this API server has access to my instance oauth token, and could have access to my account data?

**Comment by bohwaz** [comment]
Maybe it would be better to inform the user about that and allow him/her to disable push messages before the oauth dance, so that the access token is never sent to a third party?

**Comment by connyduck** [comment]
Tusky does not use tuskynotifier.keylesspalace.com anymore
