### ISSUE TITLE
[Feature Request] Share a link and extract the title, images, author's name

### ISSUE THREAD

**Issue by ebrulato** [Vavassor/Tusky#136]
<< enhancement of the "share with" feature with the ability to extract the title of a link, the author's name, the images (ask for a choice for the publication) >>

**Comment by theZacAttacks** [comment]
So you're wanting a "toot-sharing" menu kind of [like this](https://drive.google.com/open?id=1P-SKQGZvQTQIuX4qWAj0p86RF0lC6TzXQA)?

**Comment by ebrulato** [comment]
Well, I don't undestand very well the video. 
I think that it could be great to fetch some data from an url when you want to share it with Tusky on Mastodon. 
The "share with" is describe (and seems to be implemented in the next release : #52

**Comment by torrentcome** [comment]
Hi,

i will take care of it

Cheers

**Comment by Vavassor** [comment]
I forgot to tag the commit, but this was closed by pull request #291 and is merged as of commit 1935253c1814480fda11d4f6ace530a6b42f399f.
