### ISSUE TITLE
"Bot" and "Commercial" Profile Tickbox

### ISSUE THREAD

**Issue by shivian** [Vavassor/Tusky#137]
Idea: a tick box that is required to be checked if the account is a bot, and another if a bot is a commercial entity. Profiles found to be ignoring these boxes can be removed from a server without warning. All users could then have a set of options in their profiles like "mute all local bots," "mute all federated bots," and even "mute all commercial profiles," allowing them to easily control their bot / brand exposure in a flash

**Comment by theZacAttacks** [comment]
This seems more like something that would have to be implemented server-side instead of in the app.

**Comment by Vavassor** [comment]
True, this is something that'd need to be built into the Mastodon API for it to work. You could field this over at https://github.com/tootsuite/mastodon/issues.

**Comment by shivian** [comment]
Apologies, I made it on the wrong GitHub! Thanks guys!
