### ISSUE TITLE
[Feature Request] link preview 

### ISSUE THREAD

**Issue by ebrulato** [Vavassor/Tusky#141]
<< If a user send a simple link, the application try to enhance the toot by providing the image. If an image is present the application don't have to enhance the toot >>

It should support:
- youtube (I don't think reading these videos in the application is a good idea) 
- instagram
- ...

**Comment by RaphTriesCoding** [comment]
I think we should "at least" have the Youtube Video Picture, it would be better than having to click on a link without knowing where we will endup (Internet is spooky)
![screenshot_20170621-175657](https://user-images.githubusercontent.com/26653416/27394196-9a21a658-56ab-11e7-96cf-4aec5edb7846.png)

**Comment by charlag** [comment]
This is implemented as well, @connyduck
