### ISSUE TITLE
Save toots as drafts

### ISSUE THREAD

**Issue by theZacAttacks** [Vavassor/Tusky#142]
Maybe add an option to the menu bar on the side that shows your locally saved drafts

**Comment by ebrulato** [comment]
Good Idea, as we have 500c, we may need some times to write some toots :)

**Comment by raphaelm** [comment]
Currently, when adding a photo to a toot, it is instantly uploaded. In this case, would we want to store the photo locally as well or just keep the URL?

**Comment by Vavassor** [comment]
I forgot to close this when #330 was merged! I added media to drafts later in commit a1e007eb2adf23e8ae19e7810bf3acbd6ec02c21 and chose to just save copies of any attachments on external storage (SD card) and upload them when the draft is opened.

Ideally, I'd like to do it the other way, but I wanted to avoid the situation where someone loses connection, can't finish uploading, so it won't let them save the draft. You could save a local copy in that case and build extra logic to distinguish already-uploaded URIs from local copy URIs, but it was enough trouble without that, for the moment.
