### ISSUE TITLE
Incorrect Hashtag highlight in editor

### ISSUE THREAD

**Issue by yookoala** [Vavassor/Tusky#145]
The editor detects my Hashtag and highlights it blue. This is nice except it sometimes got it wrong. For example, when I type "#notepad++" in one of my post, the highlight extends to the whole string "`#notepad++`" except hashtag only goes to "`#notepad`".

The highlight should only extend to text that will become hashtag.

In the editor:
![screenshot_20170413-122706_shrink](https://cloud.githubusercontent.com/assets/91274/24990347/e736fa48-2045-11e7-8360-7c069e45824a.png)

The result ([my actual post][post-9438]):
[![2017-04-13 12-31-55 crop](https://cloud.githubusercontent.com/assets/91274/24990282/636bb960-2045-11e7-95b7-36165d9b4e47.png)][post-9438]

[post-9438]: https://mastodon.hk/@yookoala/9438

**Comment by Vavassor** [comment]
I changed it to just use the same logic as Mastodon's server (and the same for mentions) by translating their regular expressions. I figured it'd be the best way to ensure the behaviour matches.
