### ISSUE TITLE
"Copy URL" of a status to Clipboard

### ISSUE THREAD

**Issue by yookoala** [Vavassor/Tusky#148]
It would be great to have an option to "Copy URL" instead of sharing to another app. More flexible to use. There is only option to "Share" in the status' option menu.

![screenshot 2017 4 13 12_50_00 crop](https://cloud.githubusercontent.com/assets/91274/24990708/6ad92054-2048-11e7-9cc1-53349b762033.png)

**Comment by theZacAttacks** [comment]
You can share -> copy to clipboard

**Comment by yookoala** [comment]
OK. But there are Apps with that feature. And it is much more intuitive to use.

I still think its a good-to-have.

**Comment by connyduck** [comment]
This was fixed in https://github.com/Vavassor/Tusky/pull/391
