### ISSUE TITLE
Blocked users still show on timelines

### ISSUE THREAD

**Issue by raisedfist** [Vavassor/Tusky#149]
Issue: blocking users doesn't seem to work

Expected result: Blocked users' content should not show in any timeline.
Actual result: Blocked users's content show up on local/federated timelline.

On the instance's web interface this doesn't happen.

**Comment by raisedfist** [comment]
The users get blocked after force closing the app and starting again.

**Comment by Vavassor** [comment]
This might just be an issue of it having pre-loaded a bunch of posts with the blocked user still in them. And then blocking them only prevents them from showing up in newly-loaded posts.

So if that's the issue, the fix would just be to scan the lists of loaded posts and remove all the ones by the blocked user. Which I should've been doing anyway.

**Comment by Vavassor** [comment]
I forgot to tag the commit, but this was fixed in 5179d7e9b32ec191268147df3c66ee02b814457b, so it should be good in version 1.1.3.

**Comment by charlag** [comment]
@Vavassor I think you may close it then?
