### ISSUE TITLE
Add tusky on F-Droid

### ISSUE THREAD

**Issue by Dryusdan** [Vavassor/Tusky#151]
I use F-Droid (Google is evil ! (for me :-° ) ) and I like if Tusky are in F-Droid :) 
(I have download usky on Google play... But don't like :p )

Or compile .apk and let's in repository :)
Thank :)

**Comment by daycode** [comment]
duplicate of #39 .

please, use the search function to watch if an issue is already open 😄 

so, can you close this issue ?

**Comment by Dryusdan** [comment]
Yes, sorry (I forgot search bar... In real the Github search bar don't work fine ;-° )
