### ISSUE TITLE
Add Direct to visibility options panel

### ISSUE THREAD

**Issue by daycode** [Vavassor/Tusky#155]
Add the option "Direct", like in the web UI, to send a direct message to people mentionned and use the same description and icon as web UI.

![direct-message](https://cloud.githubusercontent.com/assets/13915512/25042751/acd14dd8-211a-11e7-9d60-5730dfab346f.png)

**Comment by Vavassor** [comment]
Yes, I'd like to reformat the options to be more like the main site, at the same time this is added. Especially because associating the icon with the visibility level for that drop-down is a lot more understandable than the button indicator (TOOT!, TOOT, or TOOT🔒).

**Comment by daycode** [comment]
@Vavassor I'm doing that right now, the functionnality is done and I put icons instead of radio basic style

Work in progress in mind 😄 
![visibility-panel](https://cloud.githubusercontent.com/assets/13915512/25057945/f141e572-2174-11e7-96cd-4bc964dbf184.png)

**Comment by daycode** [comment]
Can I put the content warning button like in web UI next to the visibility button instead of in the visibility panel ? 🤔

**Comment by Vavassor** [comment]
@daycode Oh nice! Yes, I was going to move the content warning to its own button like the site.
