### ISSUE TITLE
Offer to open links with Tusky

### ISSUE THREAD

**Issue by rixx** [Vavassor/Tusky#160]
This is hard because you cannot just match a URL to see if Tusky should be offered, but maybe either do it for the most popular instances, and/or the one the user configured as their own?

**Comment by daycode** [comment]
you already can share to tusky. or you talk about open an url in tusky that match a mastodon instance ? 🤔

**Comment by rixx** [comment]
Exactly, sorry for being unclear. When I hit a, say, reddit url in a browser, it'll ask me if I want to open it with the reddit app. Something similar for at least one or the most common chaos instances would be nice.

**Comment by raphaelm** [comment]
This would be possible either via a hardcoded list of domains in the AndroidManifest (hard to maintain) or via a patterns (way to many false positives). Not sure if this is feasible.

**Comment by rixx** [comment]
It could at least be provided for the instance(s) of the logged in user, I guess?

**Comment by raphaelm** [comment]
Nope, needs to be hardcoded into the app metadata, cannot be changed dynamically. (Android compiles a list of these things without starting the app.)

**Comment by rixx** [comment]
Ah well, that's not feasible then.

**Comment by daycode** [comment]
I had open [an issue](https://github.com/tootsuite/mastodon-api/issues/18) in mastodon-api to ask if it's possible to have the list of all instance in the API.

**Comment by fauno** [comment]
no idea if it supports regexes, but this one or something along this should cover mastodon:

`https?://[a-z0-9-\.]+/@\w+/\d+`

**Comment by makmm** [comment]
I would send a PR to do this using @fauno regexp, but frankly I have No Fucking Idea :tm: of how to code the part where the Activity(?) takes in the url and fetches it.

Any way, it would be something like F-Droid's logic: https://gitlab.com/fdroid/fdroidclient/blob/master/app/src/main/AndroidManifest.xml#L441

**Comment by rixx** [comment]
As mentioned above, we can't use a general http regex unless we want to offer to open either all or none urls in Tusky.

**Comment by makmm** [comment]
@rixx all or none urls of what type? I don't really understand what you mean.

**Comment by errotu** [comment]
Sorry for commenting on such an old issue. Due to current increase of Mastodon (and Tusky) users, I would be very much in favor of such a feature. It would increase the user experience substantially, in my opinion. While I see the difficulties with deciding which instance/URL should be added, maybe mirroring [the selection from joinmastodon.org](https://joinmastodon.org/communities) would be an option?
