### ISSUE TITLE
Allow to switch between users

### ISSUE THREAD

**Issue by rixx** [Vavassor/Tusky#161]
It would be tremendously useful if I could use both my management account and my regular account from Tusky.

**Comment by alerque** [comment]
This is a duplicate of #54. Whether two accounts on the same instance or accounts across multiple instances the needed functionality is the same.

**Comment by alerque** [comment]
@Vavassor This can be closed entirely as a pointer to the duplicate, you don't need multiple open issues for the same action item.

**Comment by Vavassor** [comment]
@alerque You're right. I wasn't thinking of how it'd be confusing. I was just going to close both when resolved, but that makes more sense.
