### ISSUE TITLE
Replace pencil icon by a mastodon related icon

### ISSUE THREAD

**Issue by eidolies** [Vavassor/Tusky#172]
To integrate the Tusky style into the mastodon/elephant context, I'd suggest replacing the pencil icon used to compose a new toot by a mastodon related icon such as a trunk, tusks and a trunk, or a mastodon face (with tusks and trunk).

**Comment by alerque** [comment]
The pencil is confusing anyway, generally being used for "edit". Compose is a slightly different thing and if it wasn't for the fact that that button location is generally used for new actions the icon would do nothing to make the action more understandable.

**Comment by Vavassor** [comment]
I dunno, if I saw "trunk button" or "elephant face button" I would be clueless what the button would do, where at least "pencil" has the association with writing? Also, I'm not sure this is an appropriate place for theming/branding in general.

**Comment by eidolies** [comment]
Good points.

I thought mastodons couldn't hold a pencil but alright, this is pure silliness.

**Comment by alerque** [comment]
How about just a `+` symbol?
