### ISSUE TITLE
Long toot with content warning reserves/wastes the space for the content

### ISSUE THREAD

**Issue by eidolies** [Vavassor/Tusky#173]
A long toot containing a content warning reserves the space for the content, and thus wastes the space.

Link to toot: https://mamot.fr/@eidolies/379553
###  Collapsed:
![cw1](https://cloud.githubusercontent.com/assets/787068/25067466/f640fc5e-2244-11e7-86b9-b065e339456f.jpg)

###  Deployed:
![cw2](https://cloud.githubusercontent.com/assets/787068/25067467/f8a483da-2244-11e7-9b8b-9fe1d1bc7f71.jpg)

### Doesn't happen on the web interface:
![cw3](https://cloud.githubusercontent.com/assets/787068/25067468/fb7af35a-2244-11e7-8abd-96ee9f031aa7.jpg)

**Comment by Vavassor** [comment]
This is definitely a bug in my "FlowLayout" that's used for the content warning and show more/less button. I think it's actually eating up equal amounts of space for the content warning and the button, so with long CW text it ends up with a button followed by tons of space.
