### ISSUE TITLE
https://mastodon.social/@nxd4n crashes tusky

### ISSUE THREAD

**Issue by danito** [Vavassor/Tusky#179]
When someone looks up my account https://mastodon.social/@nxd4n Tusky stops working (Android from playstore)

**Comment by connyduck** [comment]
Can reproduce, the reason is it cant handle empty media urls. Working on it, thanks for your experiments!

**Comment by danito** [comment]
Those empty media files are from an unsuccessfull atempt to upload images with php file_get_gontents(); 
Mastodon responds with a media id but this file doesn't exists and the url in the response is redirected to a undefined.png which doesn't exists (404)
