### ISSUE TITLE
Errors during posting cause Toot button to remain disabled

### ISSUE THREAD

**Issue by fpiesche** [Vavassor/Tusky#183]
If an error occurs during posting (ie. after pressing the TOOT button), this is handled with an error message appearing in the post box - however, the TOOT button remains disabled, which means users can't retry to send the post. Instead, the only option is to press copy the post, press the X to cancel out of the compose screen and re-compose the entire post.

This can happen e.g. if switching networks while a post is being sent - for example I'm seeing it a lot when I leave the house to walk the dog and try to submit a toot just before I exit the range of our home wifi.

**Comment by raphaelm** [comment]
Probably fixed in https://github.com/Vavassor/Tusky/commit/c343f9b497e3e97e24b7259a0f3bee50013e14f1
