### ISSUE TITLE
Boosts and Stars on Mention Timeline don't link to Profiles

### ISSUE THREAD

**Issue by jerezim** [Vavassor/Tusky#186]
(It may have been solved in recent versions, but because #39 I cannot tell... :/ )

On "mentions" screen, "follow" mentions have conveniently the PP of ppl following you. You can click the PP, see their profile and follow back. But "boosts" and "stars" don't... Too bad, as you may want to check who boosts and stars you (and follow them). 

Adding the PP+links to their profiles would also homogenize the interface. There is no UI reason they would be missing there when they are everywhere else in the app, is it?

<3

**Comment by Vavassor** [comment]
You can click on boost and favourites. It is a little inconsistent, for follows you click on the avatar but for boosts/favourites you can click on the whole notification.
