### ISSUE TITLE
specific toot notification causes crash

### ISSUE THREAD

**Issue by dgonyeo** [Vavassor/Tusky#188]
Whenever I open my notification and scroll down, tusky crashes as soon as it attempts to render a specific notification on the screen.

This is that notification, as fetched from the `/api/v1/notifications` endpoint on mastodon.social:

https://gist.github.com/dgonyeo/16c8f1bfe2549e2c6f771b2b7e173272

I hit the "report a problem" or whatever button android presented me, so hopefully you can get a stack trace from it via that. Not sure if I can get the stack trace myself to report here.

I also think tusky would crash for me whenever this toot was in my main tl, as when this first started happening tusky would also crash immediately upon loading my tl.

**Comment by charlag** [comment]
@dgonyeo can you please check it with one of the recent versions?

**Comment by charlag** [comment]
I think we would receive crash info if this still happened

**Comment by connyduck** [comment]
Yes I fixed this but it was not a separate commit.
