### ISSUE TITLE
Changing screen orientation after scrolling causes timeline to reload, losing scroll position

### ISSUE THREAD

**Issue by mdiehr** [Vavassor/Tusky#190]
Tusky v 1.1.2
Android 7.1.2 (Google Pixel)

Steps to reproduce:

- Start in Portrait orientation
- Navigate to "Home" timeline
- Scroll down several toots so that the top toot is not visible
- Rotate phone to Landscape orientation

Results:

- The Home timeline reloads from scratch
- The scroll position is reset to the top

Expected results:

- The timeline probably shouldn't reload from scratch
- The timeline should stay at the same scroll position when changing orientations

Notes:

This also happens for the Notifications, Local, and Federated timelines.

**Comment by theZacAttacks** [comment]
It also loses the place when you refresh, which can be frustrating.

**Comment by Vavassor** [comment]
Commit dc971ec36d7e75d2f4c109986fc6405df7ef8b8c fixes this.
