### ISSUE TITLE
Variable text size

### ISSUE THREAD

**Issue by mdburnes** [Vavassor/Tusky#192]
The toots are extremely difficult to see for people that have limited/poor eyesight. Please add an option to change the text size.

**Comment by contraexemplo** [comment]
This is a feature I wish Tusky had. I am visually impaired and it's difficult to use the app without a custom text size feature.

**Comment by connyduck** [comment]
Well Tusky supports the Android accessibility options, so when you increase font size in the Android settings, it will also increase in Tusky. Does this not work for you or why is it not sufficient?

**Comment by contraexemplo** [comment]
First of all sorry for the large screenshots, I am on mobile right now.

My settings on Android 7.1.2:
![Accessibility settings: Text size 130% and display size Large](https://user-images.githubusercontent.com/29989176/32094248-d945ae4c-badd-11e7-98da-02152c71721a.jpg)

They don't seem to affect Tusky at all:
![Tusky's home page with tiny text on toots](https://user-images.githubusercontent.com/29989176/32094289-ffe9bc46-badd-11e7-8003-92c19fef8675.png)

Mastalab has this option and it looks like this:
![Mastalab's home page with only one toot with large text](https://user-images.githubusercontent.com/29989176/32094452-8b43af2c-bade-11e7-89d6-4fc4d7352d85.png)

**Comment by connyduck** [comment]
Ok thx for the feedback! I will investigate why Tusky does not honor accessibility settings on all devices, if I find no solution I will make a font-size setting for Tusky!

**Comment by contraexemplo** [comment]
Nice! Thank you. <3

**Comment by connyduck** [comment]
@contraexemplo
ok I did some research and it looks like the font size in your screenshot is already increased by 130% (so the android accessibility feature is working), but the tusky default font size is just too small. Can you try out a test apk to verify this?

**Comment by contraexemplo** [comment]
@connyduck Yes!

**Comment by connyduck** [comment]
So here is a apk with the newest ui changes and a fontsize of 15sp. It maybe unstable since I did not yet test everything. 
https://connyduck.at/tusky-test-1.apk

**Comment by contraexemplo** [comment]
@connyduck It's definitely better to read, thank you. 

However (I don't know if you already noticed this or not), some things aren't being displayed correctly:
![Screenshot of a detail when expading a toot showing the information is displayed bigger than the space reserved to it](https://user-images.githubusercontent.com/29989176/33170506-9b00d12c-d02f-11e7-9dd3-c7cd981b4983.jpg)
![Screenshot showing a profile with counters of following, followers and toots at the same line, making everything confusing](https://user-images.githubusercontent.com/29989176/33170513-a3fbe3f2-d02f-11e7-8b33-e4299ed220fb.jpg)

**Comment by connyduck** [comment]
Ok, many thanks for your help @contraexemplo! I will fix all of that and release it with the next version!

**Comment by connyduck** [comment]
This was fixed with 1.4 😊
