### ISSUE TITLE
Unicode support in display name

### ISSUE THREAD

**Issue by eidolies** [Vavassor/Tusky#199]
Could the display name have unicode support?

How things look in browser and in Tusky (highlighted to show how the characters are superscripted):

For reference, the name is: ᵉⁱᵈᵒ|ⁱᵉˢ
There could be more complex occurences of display names out there.

### Profile in browser:
![screenshot_2017-04-19-01-57-17](https://cloud.githubusercontent.com/assets/787068/25157814/e10cd95a-24a3-11e7-94c8-4c456cec2ec9.jpg)

### Profile in Tusky
![screenshot_2017-04-19-01-55-03](https://cloud.githubusercontent.com/assets/787068/25157813/e10cdd10-24a3-11e7-84de-a4c4d51fb6c8.jpg)

**Comment by Vavassor** [comment]
This is how it shows up on my phone:
![screenshot_20170418-205553](https://cloud.githubusercontent.com/assets/8423688/25158910/e3574ca6-2479-11e7-8fe3-b8b6175f3b6f.png)

I'm not sure what font you're using, but it seems like that may be the problem?

**Comment by eidolies** [comment]
Indeed, sorry for the noise. Using it since years, it's like a default font for me. Closing, and thanks!
