### ISSUE TITLE
Infinite followers' list

### ISSUE THREAD

**Issue by SodaFormulas** [Vavassor/Tusky#2]
Hi,

I'm using Tusky version 1.0.0-alpha.5 from the F-droid repository.

I have only one follower on my Mastodon account and when I go to the Followers tab this one follower is looping infinitely. Same if I list the only follower of another profile.

On a profile with 2 followers, the two are repeated alternatively.

Cheers.

**Comment by Vavassor** [comment]
This should already be fixed in the code I have ready for 1.0.0-alpha.6. I know it has to do with it failing to detect the end of a list. I'm going to hold off closing until I've verified on other phones that it's fixed, but it _ought_ to be.

**Comment by Vavassor** [comment]
Tested checked out and I released the fix.
