### ISSUE TITLE
order of toots not right after refresh

### ISSUE THREAD

**Issue by Geobert** [Vavassor/Tusky#205]
on federate timeline, refresh manually give me wrong ordered toots (see attached image)
![tusky_bug](https://cloud.githubusercontent.com/assets/72570/25217619/8178922a-259f-11e7-8f88-5a06d1b9403f.jpg)

**Comment by boced66** [comment]
The problem sometimes happens directly to the opening of the tab,
I think of a problem of time display rather than sorting,
to check,

FR : 
Le problème arrive parfois directement à l'ouverture de l'onglet, 
Je pense à un problème d'affichage de temps plutot que de tri, 
à vérifier,

**Comment by boced66** [comment]
Second verification,
The problem also appears on the website of my instance,
So I think of a bug (or feature) of mastondon in itself,
For me this ticket may be closed,

FR :
Deuxieme vérification, 
Le problème apparait aussi sur le site web de mon instance, 
Je pense donc à un bug (ou fonctionnalité) de mastondon en lui même,
Pour moi ce ticket peut-être cloturé,

**Comment by Geobert** [comment]
true, closing
