### ISSUE TITLE
Send user agent

### ISSUE THREAD

**Issue by rixx** [Vavassor/Tusky#206]
Tusky sends "okhttp/3.6.0" as a user agent, but it would be much nicer for administrators on servers to see what apps connect.

(In this case we needed to do some troubleshooting regarding rate limiting and took some time to figure out which agent uses okhttp.)

**Comment by connyduck** [comment]
That is a really good idea. I implemented a custom User-Agent consisting of Tusky&Android version: https://github.com/Vavassor/Tusky/pull/207

**Comment by alerque** [comment]
This issue can be closed as the PR that fixes it is merged (and thanks @connyduck for the contribution!).
