### ISSUE TITLE
Download unsuccessful on f-droid

### ISSUE THREAD

**Issue by loi219** [Vavassor/Tusky#211]
I've found Tusky on f-droid, but the download failed.

**Comment by Vavassor** [comment]
It isn't supposed to be on F-Droid at all right now. Issue #39 has a bit more explanation why. I think they just removed the app data and build configuration but didn't entirely remove the page for Tusky.

I'm planning on putting a version on F-Droid without Firebase soon that will use polling for notifications. This will hopefully just be a temporary setup until the push notifications can be replaced with something that will work equally on F-Droid and google play/amazon.

**Comment by Vavassor** [comment]
Tusky's back up on F-Droid now, so the download should be all good!
