### ISSUE TITLE
[Feature Request] Custom Notification API

### ISSUE THREAD

**Issue by hinaloe** [Vavassor/Tusky#220]
The notification proxy looks need a lot capacity.  
If I can customize `tusky_web_url` on app preference, we can use (more simply) own (or other) proxy server.

**Comment by SkyzohKey** [comment]
:+1: or this, or using Pushy/MQTT to replace GCM. 🙂

**Comment by hinaloe** [comment]
Oh, its interesting! 
( the largest problem is there are no way to get push notify without websocket... )

**Comment by hinaloe** [comment]
I'd forget to think about google-service.json and near...

**Comment by connyduck** [comment]
Tusky does not use push notifications anymore

**Comment by charlag** [comment]
@connyduck how does it work now?

**Comment by connyduck** [comment]
By regularly pulling. You can change the interval in the settings. 
Its not really a good solution, I will investigate how other apps handle this, but I think we will stay with pulling for some time.
