### ISSUE TITLE
Timeline stops loading after scrolling some

### ISSUE THREAD

**Issue by KonomiKitten** [Vavassor/Tusky#225]
Basically, and quite frequently as of late the timeline (any of them) will stop loading after you have been scrolling/reading it. All you'll get is the spinning loading animation and have to reload the entire timeline losing your current position only to have it happen again.

![Screenshot](https://cloud.githubusercontent.com/assets/12713710/25315540/e45cddea-2899-11e7-88d0-4a3a8233a560.png)

**Comment by charlag** [comment]
@connyduck I'm pretty sure this doesn't happen anymore, at least I didn't see any complains about it.

**Comment by KonomiKitten** [comment]
Confirming that I don't get this issue with 1.2.1, as it seems fixed closing this bug.

**Comment by charlag** [comment]
@KonomiKitten cool. thank you!
