### ISSUE TITLE
GNU Social compatibility 

### ISSUE THREAD

**Issue by lc-guy** [Vavassor/Tusky#236]
Would it be possible to make this app compatible with GS instances too alongside mastodon? Having another client for GS would be great.

**Comment by Vavassor** [comment]
There's so many things that are Mastodon-specific in the app right now that it'd be a lot of work to make it work for GS. The API is separate and it uses a different Oauth version for login. A bunch of things are analogous, but there'd have to be logic to switch parts of the interface depending on whether you're on a GS or Mastodon account.

It'd be nice to have it as part of the project, but I'm not going to work on it personally for a long time.
