### ISSUE TITLE
Changing screen orientation while reading a long toot leads to unreadable toot

### ISSUE THREAD

**Issue by frodon1** [Vavassor/Tusky#237]
1. Open a toot with enough replies to make the scroll bar appear
2. Rotate the phone
3. Try to scroll down the toot: it is now unreadable

![screenshot_20170426-081645](https://cloud.githubusercontent.com/assets/6490878/25420748/e25a1ba4-2a59-11e7-994e-54c3f85dc510.png)
![screenshot_20170426-081656](https://cloud.githubusercontent.com/assets/6490878/25420750/e6d42756-2a59-11e7-9c69-1dcd176f5709.png)

**Comment by Vavassor** [comment]
Ah!! The duplicated timeline bugs so far haven't been something I could reproduce, so this is really really helpful! This is definitely related to Issue #20, but I suspect it's a "same symptom, different bug" scenario.

**Comment by Vavassor** [comment]
I was able to fix this by just not reloading the thread when reorienting. Unfortunately it didn't give me many clues for the duplicate item bugs when _scrolling_, but at least this one's done.
