### ISSUE TITLE
Privacy icon when tooting a toot should reflect the actual privacy setting for the toot

### ISSUE THREAD

**Issue by elad661** [Vavassor/Tusky#241]
At the moment, Tusky defaults to having the privacy-setting for a new toot the same as the last one you set, which is not a bad choice. However, sometimes I forget that my last toot wasn't public, so I look down and see the globe icon, which the web interface of Mastodon uses to indicate "public", so I think "okay it's public" and post the toot, and only then I remember that the icon does not change to reflect the selected privacy level.

If the icon changed to reflect your selected setting, you could always know the privacy level of the toot you're about to post (and adjust it accordingly if needed) without having to remember to click on it or remember what you set it to last time you used the app.

**Comment by daycode** [comment]
already done for the next update #194 and commit db021b9 😉 

so can you close this issue ? 🤔

**Comment by elad661** [comment]
Oh, cool. Closed.

**Comment by daycode** [comment]
![visibility-panel](https://cloud.githubusercontent.com/assets/13915512/25501645/c98ccc62-2b93-11e7-97ff-024a8d5099ca.gif)
