### ISSUE TITLE
App doesn't stay open once it becomes inactive (Android)

### ISSUE THREAD

**Issue by mcat-ee** [Vavassor/Tusky#242]
If i change context by pressing the Android home button, then I re-enter Tusky it starts up all over again - is this a documented problem? Are other people getting this issue or is it likely to be an issue specific to my handset/configuration?

Phone: Huawei P9
Android version: 6.0

**Comment by Vavassor** [comment]
Android can evict activities from memory when they're backgrounded so I guess on your phone it does that every time? Really, Tusky needs to save and restore state manually so it doesn't reload in this kind of situation.

The same problem pops up when you  change orientation between portrait and landscape, it causes the activity to be recreated and the timeline reloads and puts you back at the top. Annoying.

**Comment by KonomiKitten** [comment]
@mcat-ee this is part of how Android works, it will swap out apps depending on how much memory you have used if you have a phone using a lot of memory or not much memory to begin with you will see this happen.

Some apps can work around this by saving your position, but I am not familiar with the Tusky code base so I don't know how hard such a thing would be to implement (not to mention plenty of apps don't bother to go to this trouble anyway).
