### ISSUE TITLE
Image Toots require text

### ISSUE THREAD

**Issue by mcat-ee** [Vavassor/Tusky#243]
Currently it's not possible to post an image without any text characters in the post.

**Comment by Vavassor** [comment]
I think this is also true on the main site, if I'm not mistaken? Just, it automatically includes a link to the photo while Tusky doesn't. I probably should make it do that, I'm not sure.

**Comment by mcat-ee** [comment]
This is true! I'll check the Mastodon repo and file this if need be.

Thanks for the prompt response!
