### ISSUE TITLE
When changing orientation of app, 'Search accounts...' text is lost

### ISSUE THREAD

**Issue by PhotonQyv** [Vavassor/Tusky#259]
Just noticed that if while running the app you rotate the screen of your device either from portrait to landscape or vice versa the 'Search accounts...' default text disappears. Also if you search and then rotate the search criteria as entered is lost though the search results remain across rotation.

**Comment by Vavassor** [comment]
Commit dc971ec36d7e75d2f4c109986fc6405df7ef8b8c fixes this (obvs).
