### ISSUE TITLE
Oddly attached media crashes Tusky

### ISSUE THREAD

**Issue by PhotonQyv** [Vavassor/Tusky#265]
Toot below has an image attached slightly differently to what I've seen before, it opens in web client when I log into mastodon.xyz but appears blank in Tusky and crashes the app if you click on it.

Tusky view:

![screenshot_2017-05-04-11-15-21](https://cloud.githubusercontent.com/assets/27952685/25699463/3656aa44-30bb-11e7-9084-e6cbc8e1afdf.png)

Original toot: (via Amaroq, by the looks)

https://mastodon.network/users/ember/updates/50806

**Comment by PhotonQyv** [comment]
Might also be connected to mastodon.network running an earlier version on Mastodon

**Comment by connyduck** [comment]
I can reproduce it. The error occurs because the type of the media attachment is "unknown"
```
"media_attachments": [
    {
      "id": 394420,
      "remote_url": "https:\/\/mastodon.network\/system\/media_attachments\/files\/000\/276\/681\/original\/c25a86af2462ac7f",
      "type": "unknown",
      "url": "\/files\/original\/missing.png",
      "preview_url": "\/files\/small\/missing.png",
      "text_url": null,
      "meta": null
    }
  ],
```

So while I agree that this might be a problem with the mastodon api, Tusky should not crash on it.
I am working on a fix.

**Comment by wxl** [comment]
@connyduck where do I see what you're seeing? Since I don't know, [here][1]'s another potential example. 

[1]: https://mamot.fr/users/libe/updates/151143
