### ISSUE TITLE
Split code into modules

### ISSUE THREAD

**Issue by connyduck** [Vavassor/Tusky#269]
So the Tusky codebase is growing but it still consists of only two packages, one has 68 files. This is starting to get confusing. For example, *Adapter files can contain jsonadapters or recyclerview adapters.

My suggestion for meaningful packages:

- leave Application + Activities in the main package
- all fragments into subpackage fragment
- all services into subpackage service
- all json parsing related files into subpackage json
- all recycler/listview adapters into subpackage adapter
- all network related classes into subpackage network
- everything else into a utils subpackage

**Comment by Vavassor** [comment]
I did this and I think it's decently organized now? The commit is aa2394748c2d2ff2b0f0b61354a51f15f43c3c8f.

Even with android studio's fancy refactoring there was a bunch of me pasting "public " to the front of things involved.

**Comment by connyduck** [comment]
Looks good, thank you! :3
