### ISSUE TITLE
About tab doesn't load Tusky's profile page when button pressed, gives error message instead (I'm on mastodon.xyz)

### ISSUE THREAD

**Issue by PhotonQyv** [Vavassor/Tusky#279]
When I click on 'Tusky's Profile' button on About tab the profile fails to load giving a generic 'error occurred, retry' message, I'm logged into mastodon.xyz instance, so perhaps it only currently works as planned for someone on mastodon.social. 

Just checked with my mastodon.social account, it does indeed work. So the code needs to be updated to make sure it specifies the instance name for the Tusky profile, not just the account id.

**Comment by Vavassor** [comment]
Aye, it needs to be replaced with a request to the search endpoint for Tusky@mastodon.social to get the account.
