### ISSUE TITLE
App Closes after posting toot while rotated.

### ISSUE THREAD

**Issue by BanjoFox** [Vavassor/Tusky#287]
When I compose my toots I do it with my phone rotated (landcape mode). 
If the phone, and therefore the app, stays in that mode when I hit the "TOOT!" button the app immediately closes. Re-opening the app I do see that the my toots have posted successfully.

The strange thing is that if I compose the toot and then go back into portrait mode and submit, there is no issue. Very strange.

Running version 1.1.3 
Nexus 6x, "stock" Android 7.1.2

**Comment by charlag** [comment]
I couldn't reproduce it, feel free to reopen if you're still affected.
