### ISSUE TITLE
Light Theme [Tusky v1.0.1]

### ISSUE THREAD

**Issue by KonomiKitten** [Vavassor/Tusky#29]
Feature request to at some point have the Light Theme come back which I can't find in version 1.0.0.

**Comment by Vavassor** [comment]
Yeah, it's still in the codebase, actually. I just disabled it for 1.0.0 because parts of it were showing up inconsistently because of all the work on the dark theme. I'd like to go through and fix the broken bits and make it as polished as the dark version and re-enable it in a future update.

**Comment by KonomiKitten** [comment]
Great news, will await the update for it to be readded.

**Comment by Vavassor** [comment]
It's now an option again as of 1.1.0!

**Comment by KonomiKitten** [comment]
Yay, thank you!
