### ISSUE TITLE
Just wanted to inform

### ISSUE THREAD

**Issue by FlorentAnders** [Vavassor/Tusky#293]
Hello folks,

I just wanted to inform you that I am planning to work on a new Mastodon client based on Tusky. I have done my homework and learned my lesson, I will still publish the app with an interstitial when starting the app, but modify it again to my own liking, mention Tusky as a preference AND publish the app under GPLv3. That's okay I guess?

Greetings!

**Comment by FlorentAnders** [comment]
Online now. Everything okay?

https://github.com/FlorentAnders/Panoramic

**Comment by alerque** [comment]
Many of the new files in your fork are littered with copyright notices that are incompatible with extending a GPL project:

    

If you are going to fork and extend a GPL based project you are required to release your modifications under the terms of the GPL as well. This is the basic premise of copy-left licensing. In other words you may not stipulate extra terms like retaining copyright or demanding people request your permission. By necessity, any code you write and include in the repository that modifies or extents the base program will be legally bound to the GPL, not to any notice like the above.

Additionally, threatening DCMA takedowns is more than a little bit pretentious given your own history of license violations and the fact that you aren't the primary upstream source for this code.

>  Copying the app and not releasing your source code will follow in a Digital Millenium Copyrights Act request that will result in a takedown of your app. I am serious about this.

For the sake of your own reputation in OSS circles I suggest you just drop that line. At most end the previous sentence with "…provided you also release the source code under the terms of the GPL." Respect has to be earned, not demanded.

**Comment by FlorentAnders** [comment]
Okay, I'll release corrections following your suggestions. Greetings.

**Comment by FlorentAnders** [comment]
Leaving a 1-star review only because there are not many modifications so far (and where is the problem about adding Firebase?!) is really unnecessary. I'll correct what you wrote in your post in a few hours.

**Comment by alerque** [comment]
I reviewed the software _as it is published now_ now what you claim will come of it in the future. Play Store reviews are not for future versions. Currently you move the toolbar to the bottom (which is contrary to Android UI guidelines), change up some colors and icons, **add advertising** and call it revolutionary. As far as I'm concerned that all adds up to a major step backwards from what people could get with the original client, hence my negative review.

Note my review was generous in not bringing up the minor licensing issues as noted in this issue or the past history of the project. I reviewed the software as it is now and and as I see it being relevant to people looking for Mastodon clients.

**Comment by FlorentAnders** [comment]
You should check the Android UI guidelines about bottom bars as this is not a toolbar... okay for the rest.

**Comment by FlorentAnders** [comment]
Changes you suggested are merged.

**Comment by grawlinson** [comment]
>merged

Really? This statement in your readme is self-contradictory.

>Panoramic is licensed under the GNU General Public License version 3. This means that you can use the code and publish your own fork of the app. Copying the app and not releasing your source code will follow in a Digital Millenium Copyrights Act request that will result in a takedown of your app. I am serious about this.

Considering all of your apps are ripped from FOSS and the only "feature" you've added is advertising, you are not serious about this.

**Comment by FlorentAnders** [comment]
As I can see, the old text is not the current anymore. 

And to be honest, I would be interested in knowing from which apps mine are ripoffs, Touch for example??
