### ISSUE TITLE
Feature request: Hide searchbar option

### ISSUE THREAD

**Issue by dimqua** [Vavassor/Tusky#295]
Please implement an option to hide searchbar.

**Comment by alerque** [comment]
See also #67. In fact this is basically a duplicate feature request except my idea wasn't to make it optional but to permanently move it somewhere else more befitting its usefulness to save space.

**Comment by Vavassor** [comment]
I've moved the search bar to its own page entirely as part of addressing issue #67, so this issue isn't relevant anymore.
