### ISSUE TITLE
Privacy statut management within answer

### ISSUE THREAD

**Issue by GuyM-31** [Vavassor/Tusky#304]
If privacy statut have been set to "direct" any futher answer can't be "public".
If in the last toot, you set privacy to "direct" next toot will "direct" (this is normal) but if you answer you can't set then privacy statut to "public", the "public" staut is disabled (greyed).
If in the last toot, you set privacy to "public" next toot will "public" (this is normal) then if you answer and you set the statut to "direct", "public" statut is geyed and you can't set it back to public and then the next answer statut (even if you didn't send the previous answer) will be "direct" and the text of "public" entry is grey (but not the icon).
It can be test even without sending any toot.

Si vous avez mis le statut de confidentialité à "direct" vous ne pouvez mette en"public" les réponses suivantes.
Si vous avez pouété "direct" le pouet suivant sera "direct" (normal), mais si vous répondez, vous ne pouvez mettre le statut "public", l'entrée n'est pas disponible (grisé).
Si vous avez pouété "public" le pouet suivant sera "public" (normal) puis si vous répondez en mettant "direct" alors l'entrée "public" est grisée et vous ne pouvez plus mettre "public" et alors le statut de la réponse suivante (même si vous n'avez pas validé la réponse précédente) sera "direct" et le texte de l'entrée est grési (mais pas l’icône).
Les tests peuvent être menés sans envoyer un pouet.

**Comment by Vavassor** [comment]
I forgot to tag this issue, but this was fixed in commit 1dc9c87c2e372e67aa476fa28c4d4596bd94f7fc. "public" visibility was disabled for every reply.
