### ISSUE TITLE
Follow requests lead to logout confirmation

### ISSUE THREAD

**Issue by wxl** [Vavassor/Tusky#307]
In 1.1.4-beta.3, tapping follow requests leads to a dialog that asks if you want to log out. Follow requests are not shown after canceling the dialog. Accepting it and getting a new OAuth token does not change the behavior.

**Comment by Vavassor** [comment]
Wow, as far as I can tell this was just a re-numbering error introduced back in commit 9b86c93e765edd1ca41570580df699a7ce932918 (when the about page was added). The menu items were re-numbered, but the code that adds the follow request button when it's a locked account was NOT updated to follow the new numbering scheme.

So, it was a one-character fix of changing a 6 to a 7. Kind of feel bad I hadn't caught that, meaning that feature's been broken for a month and I hadn't known.
