### ISSUE TITLE
Media quick close [Tusky v1.0.1]

### ISSUE THREAD

**Issue by KonomiKitten** [Vavassor/Tusky#31]
Having the ability to close open media quickly would be a great feature. As of the 1.0.0 release there is no way to close a media zoom/link without pressing the back button, adding the ability to swipe up to dismiss or some other direction would make navigation much better.

**Comment by Vavassor** [comment]
Clicking outside the photo closes the photo viewer, but I figured also allowing a swipe to dismiss it doesn't hurt. Though, if you start zooming in there's ambiguity between whether you're trying to pan down or dismiss the viewer, so it assumes you're trying to pan.

**Comment by KonomiKitten** [comment]
I'm not sure how there would be ambiguity between zoom and pan down, zoom on mobiles has always been a two finger action and pan down has always been a one finger action?

**Comment by Vavassor** [comment]
I was just trying to say: after zooming in, I'd try to pan around but panning downward would just close the viewer. So I made the concession that while initiating zoom the swipe-to-dismiss is disabled.

**Comment by KonomiKitten** [comment]
Whatever needs to be done for it to work though the Twitter client seems to handle both conditions without issue.
