### ISSUE TITLE
FDroid version out of date?

### ISSUE THREAD

**Issue by MicroJoe** [Vavassor/Tusky#310]
I am using the FDroid client that is in 1.1.3 ATM.

The version is not working anymore on up-to-date instances. I want to know if there was API breaking changes that explain why 1.1.3 does not work anymore on my setup or if I should investigate elsewhere.

**Comment by Strubbl** [comment]
1.1.3 is the latest release. There are only newer beta version.

**Comment by daycode** [comment]
1.1.3 works fine in mastodon.social who have the latest release 😉

**Comment by Strubbl** [comment]
social.tchncs.de (1.4.3) even has a newer mastodon release than mastodon.social (1.4.2)
I do not want to move to mastodon.social cause distribution is a key of this system. And it should work with other instances as well.

**Comment by Vavassor** [comment]
@MicroJoe Hmm, 1.1.3 works for me on glitch.social, which according to it's about/more page is on Mastodon 1.4.3. What is it doing, exactly? Is it outright crashing, failing to login, or what?

**Comment by MicroJoe** [comment]
Turns out that this was a problem with my instance's TLS configuration. My instance owner was using `ssl_ecdh_curve secp384r1;` which is incompatible with my Android 7 phone so he managed to fix it.

Sorry for the inconvenience and keep the good work going! 👍
