### ISSUE TITLE
Mentioning multiple accounts with same username bugs

### ISSUE THREAD

**Issue by Zatnosk** [Vavassor/Tusky#312]
When showing a post in Tusky, where the author have mentioned multiple accounts with the same username but different instance names, results in every name linking to the account of the first instance mentioned.

Example post: https://manowar.social/@zatnosk/190918

**Comment by Vavassor** [comment]
Ooof, that's a pretty annoying bug. I'd imagine there's a lot of posts where people list their various aliases that get rendered useless.
