### ISSUE TITLE
Crash after attempting to open a profile of a user that does not exist

### ISSUE THREAD

**Issue by mistermantas** [Vavassor/Tusky#317]
To reproduce, make a toot like this:

```
@testerboo yeah
```

Then click on @testerboo. Assuming there's no such user with that name on the instance, app crashes.

**Comment by Vavassor** [comment]
This was fixed in commit ef607016275c40677c1c9419f9e04dea90ebc173. Now nonexistent user mentions aren't linked, they're just plain text. I was working on issue #312 and this got done in the same go.
