### ISSUE TITLE
App immediately closes upon loading. 

### ISSUE THREAD

**Issue by Starless-Night** [Vavassor/Tusky#324]
It will load up with the little logo loading screen and go the very beginning of the main page but then the app will close. The app was fine before this just started 2 days ago.

**Comment by Vavassor** [comment]
Are you using the 1.1.4-beta.4 version or 1.1.3? I'm just trying to figure out if it's something changed in the new beta or something unrelated to the app updating.

**Comment by Starless-Night** [comment]
whatever the latest one on f-droid is. I didn't sign up for any special beta version.

**Comment by Starless-Night** [comment]
I just updated f-droid and it's working fine now. thank you for your time.

**Comment by Vavassor** [comment]
Oh? Well, I'm glad to hear there's no trouble now.
