### ISSUE TITLE
Crash on trying to delete draft

### ISSUE THREAD

**Issue by charlag** [Vavassor/Tusky#339]
build.board: msm8996
build.bootloader: unknown
build.brand: Xiaomi
build.cpu_abi: arm64-v8a
build.cpu_abi2: 
build.device: capricorn
build.display: lineage_capricorn-userdebug 7.1.2 N2G47O a5d27ca598 test-keys
build.fingerprint: Xiaomi/capricorn/capricorn:6.0.1/MXB48T/V8.2.4.0.MAGCNDL:user/release-keys
build.hardware: qcom
build.host: build2.dev.xda-developers.com
build.id: N2G47O
build.manufacturer: Xiaomi
build.model: MI 5s
build.product: capricorn
build.radio: TH20c1.9-00078
build.serial: 609a644a
build.tags: test-keys
build.time: 1495631507000
build.type: user
build.user: luk1337
version.codename: REL
version.incremental: a5d27ca598
version.release: 7.1.2
version.sdk_int: 25

07-15 09:47:10.482 E/AndroidRuntime(29577): FATAL EXCEPTION: main
07-15 09:47:10.482 E/AndroidRuntime(29577): Process: com.keylesspalace.tusky, PID: 29577
07-15 09:47:10.482 E/AndroidRuntime(29577): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at com.keylesspalace.tusky.SavedTootActivity.delete(SavedTootActivity.java:134)
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at com.keylesspalace.tusky.adapter.SavedTootAdapter$TootViewHolder$1.onClick(SavedTootAdapter.java:127)
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at android.view.View.performClick(View.java:5637)
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at android.view.View$PerformClick.run(View.java:22433)
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at android.os.Handler.handleCallback(Handler.java:751)
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at android.os.Looper.loop(Looper.java:154)
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at java.lang.reflect.Method.invoke(Native Method)
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-15 09:47:10.482 E/AndroidRuntime(29577): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Vavassor** [comment]
I think this one got fixed in commit f37bb694f186fde6eadbe5743b3fa6b92e404f00?

**Comment by charlag** [comment]
@Vavassor no idea, will check the last version and close it if it's fixed

**Comment by daycode** [comment]
it works now, so can you close this issue ?
