### ISSUE TITLE
Failed getting a login token

### ISSUE THREAD

**Issue by KonomiKitten** [Vavassor/Tusky#346]
The latest release v1.1.4-beta.6 always fails to get a login token for me now, previous versions did not. I also tested with Firefox, Chrome and Jello (LineageOS' Browser), all failed. This was with the awoo.space instance. So in summary:

**Issue:** Failed getting a login token
**Version:** 1.1.4-beta.6
**Default Browsers Tested:** Firefox, Chrome and Jello
**Instance:** awoo.space

**Comment by matlink** [comment]
I've got the same issue with version 1.1.3 and mamot.fr

**Comment by KonomiKitten** [comment]
> @matlink
> By uninstalling-reinstalling it works.

Unfortunately this did not work for me.

**Comment by matlink** [comment]
Hum you're right, I was confused between versions

**Comment by KonomiKitten** [comment]
I'd like to note the WHAT'S NEW page for the Beta has this written on it:

> Fixes faulty security provider causing connection to fail.

This doesn't fix this issue, just to clarify.

**Comment by Vavassor** [comment]
@KonomiKitten Yeah, it was **intended** to fix the security provider, but it certainly didn't. I've removed the provider in 1.1.4-beta.7 just now. I … _suppose_ that'd mean this could be closed, although I didn't really fix the problem so much as take it out.

**Comment by KonomiKitten** [comment]
> @Vavassor I … suppose that'd mean this could be closed, although I didn't really fix the problem so much as take it out.

I think a new bug reporting as todo and bug with the title of "Implement improved security provider" would be the way to go, whatever you think is best.

**Comment by charlag** [comment]
@KonomiKitten could you please test it with one of the recent builds? This seems to be pretty serious and I'm not sure how many people are affected. Same for #348 I guess.

**Comment by KonomiKitten** [comment]
Haven't had this problem for awhile and it seems fixed in the current version I use 1.2.1.

**Comment by charlag** [comment]
@KonomiKitten good news! Thank you.

**Comment by KonomiKitten** [comment]
I'll do a fresh install of Tusky tomorrow to make sure this is fixed and close this bug if it is. Just want to make sure before I close it.

**Comment by charlag** [comment]
@KonomiKitten that would be very nice of you, keep us updated

**Comment by KonomiKitten** [comment]
Fixed, commenting and closing.

**Version:** 1.2.1
**Default Browsers Tested:** Firefox, Chrome
**Instance:** awoo.space

Note: I did have Jello (LineageOS Browser) fail to authenticate because it believes that oauth2redirect:// is not a valid URL scheme, but I am pretty sure this is just a bug with Jello and nothing to do with Tusky.

**Comment by charlag** [comment]
@KonomiKitten awesome news, thank you!
I thinks we should implement alternate login scheme sometime later anyway because browsers fail us a lot.

**Comment by clement-analogue** [comment]
I just installed Tusky 1.2.1 and I have this issue with both Chrome and Firefox. My instance is toot.forumanalogue.fr

**Comment by randynose** [comment]
I just picked up an Acer Chromebook today, and I'm having issues with getting a Login Token. - I tried to uninstalling Tusky, and clearing out my browser cache before opening a ticket. 


![c728423c3e755860](https://user-images.githubusercontent.com/18078909/63656787-176ba400-c767-11e9-952b-b6c5182325ac.png)

![eea4cfd14c500871](https://user-images.githubusercontent.com/18078909/63656781-07ec5b00-c767-11e9-97ae-69e48daf9cea.png)

* * * *
- Tusky Version: 8.1 Current version on Google Play
- ChomeOS version 76.0.3809.102
- Acer Chromebook Spin 11 CP311-1H-C1FS 
- Mastodon instance (if applicable): Fosstodon.org
