### ISSUE TITLE
Problems loading.

### ISSUE THREAD

**Issue by Starless-Night** [Vavassor/Tusky#349]
About half the time I use this Tusky, usually after I've already opened it and I'm switching to it from a different app, the content won't l load on any tab but the one I left it on. If I left it on federated and I tap local it's just blank. When I try to type into the search the letters don't show on the bar. The only way to fix it is to completely close the app and re-open it.

**Comment by Starless-Night** [comment]
I'm on the f-droid version if that makes a difference.

**Comment by charlag** [comment]
@Starless-Night which version is that? May it be the one with problematic security provider? Did it happen on the previous versions?

**Comment by Starless-Night** [comment]
On F-droid I;m using the most up to date version which on there it says it's version 1.1.3. That's the only version I've used so I don't know if it happened on previous versions.

**Comment by charlag** [comment]
@Starless-night could you please try the last beta (from the http://tusky.keylesspalace.com/ for example) and report if it still happening? If it does, please add info about your Android version/phone model.

**Comment by Starless-Night** [comment]
From the limited trial and error I just ran on the beta, the problem seems to be fixed :)
The phone I have is a oneplus 2

**Comment by charlag** [comment]
@Starless-Night glad to hear that! I think this can be closed now then.
