### ISSUE TITLE
Duplicated parts of the timeline [Tusky v1.0.1]

### ISSUE THREAD

**Issue by KonomiKitten** [Vavassor/Tusky#35]
I'm frequently seeing both my home and federated timeline having duplicate posts, in one case my own post appeared twice (it didn't get boosted so that isn't the problem) this makes using Tusky difficult and confusing, I feel that this should be a priority bug fix. Version is Tusky 1.0.1.

**Comment by KonomiKitten** [comment]
I forgot to mention this is happening on version 1.0.1.

**Comment by KonomiKitten** [comment]
For some reason 1.0.3 notifications seem to be working again, was there any code changes between 1.0.1 and 1.0.3 that would fix notifications?

**Comment by Vavassor** [comment]
There was a bug fixed in 1.0.2 where the enable/disable notifications preference could get stuck either off or on. Also, the notification server was down for a day or so earlier in the week.

**Comment by KonomiKitten** [comment]
@Vavassor okay I think I was probably affected by those two issues when I reported this and not a bug within how Tusky handles notifications itself, so closing this.
