### ISSUE TITLE
The redirect uri included is not valid.

### ISSUE THREAD

**Issue by Tvax** [Vavassor/Tusky#356]
I get this error: "The redirect uri included is not valid." when I try to login on mstdn.io
Does that come from Tusky ?

**Comment by Vavassor** [comment]
It's a message that mstdn.io sent back in response to a request Tusky made. I've only seen it pop up due to an old bug I caused. That was fixed by clearing app data for Tusky. But if that doesn't work, let me know!

**Comment by Tvax** [comment]
Thanks it solved it !
