### ISSUE TITLE
Crash on startPostoponedEnterTransition

### ISSUE THREAD

**Issue by charlag** [Vavassor/Tusky#357]
It is a bug I introduced while adding activity transitions for gallery.
It probably happens when fragment is detached but file loading just ended.
It also shows that fragment may be leaked to the Picasso but I'm not sure how it holds reference.
Should add LeakCanary and check it properly.

Log:
build.board: msm8996
build.bootloader: unknown
build.brand: Xiaomi
build.cpu_abi: arm64-v8a
build.cpu_abi2: 
build.device: capricorn
build.display: lineage_capricorn-userdebug 7.1.2 N2G47O a5d27ca598 test-keys
build.fingerprint: Xiaomi/capricorn/capricorn:6.0.1/MXB48T/V8.2.4.0.MAGCNDL:user/release-keys
build.hardware: qcom
build.host: build2.dev.xda-developers.com
build.id: N2G47O
build.manufacturer: Xiaomi
build.model: MI 5s
build.product: capricorn
build.radio: TH20c1.9-00078
build.serial: 609a644a
build.tags: test-keys
build.time: 1495631507000
build.type: user
build.user: luk1337
version.codename: REL
version.incremental: a5d27ca598
version.release: 7.1.2
version.sdk_int: 25

07-23 22:09:39.210 E/AndroidRuntime(16612): FATAL EXCEPTION: main
07-23 22:09:39.210 E/AndroidRuntime(16612): Process: com.keylesspalace.tusky, PID: 16612
07-23 22:09:39.210 E/AndroidRuntime(16612): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startPostponedEnterTransition()' on a null object reference
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at android.support.v4.b.a.d(ActivityCompat.java:2055)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at com.keylesspalace.tusky.b.h.b(ViewMediaFragment.java:6271)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at com.keylesspalace.tusky.b.h$5.a(ViewMediaFragment.java:163)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at com.c.a.l.a(ImageViewAction.java:51)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at com.c.a.t.a(Picasso.java:558)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at com.c.a.t$1.handleMessage(Picasso.java:1510)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at android.os.Looper.loop(Looper.java:154)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at java.lang.reflect.Method.invoke(Native Method)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-23 22:09:39.210 E/AndroidRuntime(16612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Vavassor** [comment]
Oh, I started to address this in commit 30d7f269deabce505b3dba9eb1bd032b49db4802 by just delegating the task to the ```PhotoActionsListener``` so the reference wouldn't be null at least. But I forgot to add in the bit that cancels the callback.
