### ISSUE TITLE
Build failed on F-droid for 1.1.4

### ISSUE THREAD

**Issue by daycode** [Vavassor/Tusky#361]
The automatic build failed on f-droid, more info here https://f-droid.org/wiki/page/com.keylesspalace.tusky/lastbuild_25

**Comment by Vavassor** [comment]
Argh! I was really hoping F-Droid wouldn't pick that up. The first time I committed the 1.1.4 release it had a missing asset, but I forced pushed another commit over it to replace it. Will F-Droid pick it up their next build cycle or do I have to resolve this manually somehow?

**Comment by daycode** [comment]
I really don't know 😞

**Comment by daycode** [comment]
perhaps open an issue here : https://gitlab.com/fdroid/fdroiddata/issues ?

**Comment by dimqua** [comment]
@Vavassor probably, you can make 1.1.4.1 release to solve this problem.

**Comment by tdelmas** [comment]
FDroid now show a 1.1.4 so I guess the problem is solved?

**Comment by Vavassor** [comment]
I made this [gitlab issue](https://gitlab.com/fdroid/fdroiddata/issues/820) and it was taken care of. It should be released now!
