### ISSUE TITLE
Many alerts for notification update

### ISSUE THREAD

**Issue by Vavassor** [Vavassor/Tusky#363]
Referencing this report: https://mastodon.social/@gamehawk/14317088

If you get a lot of notifications at once, it does two quick alerts when it should just be doing the alert once.

**Comment by charlag** [comment]
It *may* be solved by #431. My guess is that multiple alerts fired simultaneously and service was launched multiple times. Just leaving it here to not forget.

**Comment by connyduck** [comment]
I worked over the notifications twice in the meantime, I am pretty sure that it is fixed.
