### ISSUE TITLE
No spellchecking in posts

### ISSUE THREAD

**Issue by Phyks** [Vavassor/Tusky#374]
Hi,

First, thanks for this great Mastodon app! Not sure if intentional or not, but when writing a new post, there does not seem to be any spellchecking available (from Android).

I am using Android 4.2.2 and stock keyboard, and usually I have autocorrection / spell checking, but it does not appear in the Tusky's field to post a new status.

Thanks!

**Comment by charlag** [comment]
@Phyks I am affected by this as well, it may be fixed in repo already, I will check it later.

**Comment by jeroenpraat** [comment]
I mentioned this a while ago on Mastodon. So yes, I'm affected too.

**Comment by iknownothingaboutcomputers** [comment]
This is a bummer. I hope it gets resolved in the near future.

**Comment by connyduck** [comment]
I am guessing we need to add "textAutoCorrect" to the android:inputType of the TextView. But I can't confirm it because it works on all my devices anyway. Would be cool if somebody could try this out.

**Comment by KindlyFire** [comment]
I am affected too.

**Comment by connyduck** [comment]
So this commit https://github.com/Vavassor/Tusky/commit/d9bbb1be71a04edfd4e3b1d999b215941fdfaf57 should fix the problem, please try it out and report back :)

**Comment by KonomiKitten** [comment]
This is fixed for me as of Tusky 1.2.1 Playstore version.

**Comment by KindlyFire** [comment]
Can confirm it works !

**Comment by connyduck** [comment]
Great :3

**Comment by Phyks** [comment]
I can confirm it works, thanks!

However, there is only the spell checking in the field, not the autocorrection, I think (see the line between the field and the keyboard in http://i.utdstc.com/screen/android/desc/google-keyboard.png). Not a big deal though.

**Comment by charlag** [comment]
We need one more flag then 😅 but it can be bad for nicknames I suppose

**Comment by connyduck** [comment]
So should we also remove the InputType.TYPE_TEXT_FLAG_AUTO_CORRECT in addition to the InputType.TYPE_TEXT_FLAG_AUTO_COMPLETE? (this is confusing as I can not test it myself)

**Comment by Phyks** [comment]
I'm mainly using Tusky as a fallback when I only have my phone, and usually use Mastodon only on my laptop. Then, I don't have much experience with the interface and am not sure how bad removing the flag could be in terms of UX :/ I'd rather let other commenters with more experience post about it :)

**Comment by charlag** [comment]
@connyduck as no one else seems to be testing it, we can either ask people on Masto to try a special build with a flag included or just include both AUTO_COMPLETE and AUTO_CORRECT. We should be concerned about usernames, though, they should not be corrected.

**Comment by connyduck** [comment]
I would just release it as it is now and then ask people to test the normal build, if there are still problems we remove the other flag in the next release as well.

**Comment by charlag** [comment]
@connyduck sounds good to me.

**Comment by charlag** [comment]
@connyduck I am a little bit confused about this. Is this a blocker for the 1.3 release? Should we add a flag? Should we remove a flag? I already said that I think both should be there.

**Comment by connyduck** [comment]
No, as I said I am going to release it as it is now and then wait for feedback. If people still have problems, we need to remove the other flag from the input as well.

**Comment by charlag** [comment]
Thanks. Lets remove it from the milestone then?

**Comment by connyduck** [comment]
Haven't heard of this anymore, so i assume it is fixed 😊
