### ISSUE TITLE
Garbled main feed after posting an image

### ISSUE THREAD

**Issue by redsPL** [Vavassor/Tusky#376]
After posting a photo, i've got this on my feed. Notice that it's only on the main feed. Refreshing didn't do a thing. When scrolled, one part of the feed moves, and the 'old one' is stationary.
![screenshot_2017-08-23-15-26-17-830_com keylesspalace tusky](https://user-images.githubusercontent.com/22369758/29618262-e44e521a-8817-11e7-8e96-d8b2744886fb.png)
![screenshot_2017-08-23-15-24-44-075_com keylesspalace tusky](https://user-images.githubusercontent.com/22369758/29618295-f9fb5572-8817-11e7-856a-d7572aab6510.png)

**Comment by connyduck** [comment]
This is a known bug and will be fixed in the next release :)
https://github.com/Vavassor/Tusky/commit/8441c52b4e7436b5308e8f8b2ebf7143c7559380

**Comment by redsPL** [comment]
ok, thanks for the info, closing issue :)
