### ISSUE TITLE
Tusky crashes while typing reply

### ISSUE THREAD

**Issue by averageunicorn** [Vavassor/Tusky#379]
More often than not, Tusky crashes while I am typing a reply to another toot. It crashes after the first few letters.

It started some time ago. Until yesterday, sometimes it would crash on the first 2 tries but the 3rd would work. It wasn't as frequent either, only today it started to happen almost every time, and sometimes no matter how often I try.

I'm on cybre.space, and someone from todon.nl is having the same problem. I was on computerfairi.es until recently and used Tusky for that account, but I don't remember if it actually happened then or how frequent it was, sorry.

And another thing that I noticed:
Today, it happened twice that right after Tusky had crashed a few times because I really wanted to write a reply, Tusky wouldn't post or load things anymore, and web cybre.space gave me a "429 Throttled" error (I saw that only once, I might have missed it the first time though because it took me some time to log in).
I have no idea if this can be related. And if it is, if it's Tusky's fault or my instance's. I decided to mention it though, as it at least correlates.

I'm using version 1.1.4 with Android 6.0.1 on an Asus Zenfone Laser.

edit: I got Nougat shortly after that, and haven't had this problem since.

**Comment by Gildas-GH** [comment]
I have the same problem: some times Tusky crashes after the ~third letter. It happens mostly when I answer to another toot.
I think this is just before the mention suggestion appears, when I type slower after re-launching the app everything is ok and the suggestion appears
(What I mean with mention suggestion: https://gh.becauseofprog.fr/up/tusky-mention-suggestion.png)

**Comment by achilleas-k** [comment]
Same here. Doesn't need to be a reply, per se. Also crashes if I manually add a mention to a toot.

**Comment by connyduck** [comment]
I think this was fixed in https://github.com/Vavassor/Tusky/commit/4f96d850cc9a2807d61076ef50ed1dbd6e54b339
Please report again if it still happens in 1.2.0.
