### ISSUE TITLE
Add indication on privacy level on newly composed toot without clicking on the globe

### ISSUE THREAD

**Issue by mkosler** [Vavassor/Tusky#38]
It's pretty easy to forget what the privacy level of my last toot was. Since the privacy level is persistent at each toot, I often come back and accidentally send out a private toot that was meant to be public. Right now, the only way to know what the current privacy level is set at is by clicking on the globe icon as if I was going to change that setting. It would be nice to have some small indicator of the privacy level of the toot immediately visible on the Compose tab.

**Comment by Vavassor** [comment]
I added the indicator to the send button like how mastodon.social has it. It's not crystal clear and I'd like to also have the icon indicator but I need to reformat the controls a bit before I do that.
