### ISSUE TITLE
No notification upon image download

### ISSUE THREAD

**Issue by MicroJoe** [Vavassor/Tusky#381]
When I click the upper-right download icon when an image is showed, I get no notification nor toast to indicate me that the download has started. Hence I click the button multiple times to check if it was a miss click and there are x copies of the same image in my download folder.
Proposed solution is to use the system notifications for download or at least show a toast to indicate that the download has started.

**Comment by connyduck** [comment]
There is a notification while the file is downloading. Maybe the file was very small or your network so fast you didn't see it?
Anyway, this is confusing and I think we should implement a notification that stays on the screen after the download finished.

**Comment by MicroJoe** [comment]
My network is *very* fast right now (>300 Mbps) but even in LTE the download is too fast to see something. There should be something to tell me that download was successful as you said.

Le 2 septembre 2017 20:18:58 GMT+02:00, Konrad Pozniak <notifications@github.com> a écrit :
>There is a notification while the file is downloading. Maybe the file
>was very small or your network so fast you didn't see it?
>Anyway, this is confusing and I think we should implement a
>notification that stays on the screen after the download finished.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Vavassor/Tusky/issues/381#issuecomment-326761356

-- 
Romain Porte

**Comment by flyingrub** [comment]
https://github.com/Vavassor/Tusky/issues/388 duplicates

**Comment by connyduck** [comment]
This was fixed in https://github.com/Vavassor/Tusky/pull/389
