### ISSUE TITLE
More arabic translations pushed

### ISSUE THREAD

**Issue by BoFFire** [Vavassor/Tusky#383]
Hi,
Please find additional translation in arabic here : https://www.transifex.com/opendz/tusky-in-arabic/language/ar/

https://bin.op.tn/?859151e66ef3b8c8#R/IsTmDuXidgibIF3DfRCDdJJZIvWOepLiY7NpAxng4=

Regards,

**Comment by charlag** [comment]
Links are 403 and 502, im sorry.
Could you please try to edit strings.xml? It's not that hard and Studio even has a translations editor.
