### ISSUE TITLE
Usernames in profile are opened in browser

### ISSUE THREAD

**Issue by maxxer** [Vavassor/Tusky#384]
While they should be viewed inside the app.

![screenshot_2017-09-12-19-27-39-222_com keylesspalace tusky](https://user-images.githubusercontent.com/240201/30340672-8c620a2e-97f3-11e7-9f87-5d728e6de3cc.png)

As it happens with usernames in toots (lower in the screenshot opens fine in app)

**Comment by charlag** [comment]
I don't think it's possible. Try it in the web UI, it opens a new page with profile (because description is just HTML). We don't know if the link is leading to a profile or not.

**Comment by maxxer** [comment]
what a shame ;)

**Comment by charlag** [comment]
Just OSStatus Legacy

**Comment by Vavassor** [comment]
I was thinking: run the mention regex over the profile text to get any usernames and then feed a list of those to the search API call. Then, the links could be replaced for all the names that are found.

But in the above case it would only work for users on mastodon.social. Other instances it wouldn't find the short-name ```@Vavassor``` without the ```@mastodon.social``` on the end. So, before doing the search I guess you could fully-qualify the name by extracting the domain from the original link. Or just using the instance name of the account the profile is on?

**Comment by charlag** [comment]
I am not sure that we can really do something about it. There can be arbitrary links in the profile. Also we should remember that the profile can come from anywhere in the Fediverse - I wouldn't risk implementing a thing which would yield incorrect results. I think web versions opens another tab for a reason.
Any thoughts on this, @Vavassor ?

**Comment by charlag** [comment]
Oops, I wanted to mention @connyduck actually 😅

**Comment by connyduck** [comment]
Yes we can not do anything about it unfortunately, we would need server support, like a Mentions[] array. Maybe we should open an issue over at Mastodon.
