### ISSUE TITLE
Want a "always show nsfw/sensitive content" option 

### ISSUE THREAD

**Issue by lenchan139** [Vavassor/Tusky#385]
Sometime I search some nsfw images. Currently I need click each tool to show that content. Would you add a option that make show nsfw directly and without warning? :) thx.

**Comment by charlag** [comment]
I think it's possible but i don't know if we have time for this (sorry).
If you could do it, it would be awesome.

**Comment by lenchan139** [comment]
ok, I made a pull request :)

**Comment by charlag** [comment]
Wow, cool, didn't think it will work just like that :D
