### ISSUE TITLE
"Upstream Code is Not Entirely Free"

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [Vavassor/Tusky#387]
F-Droid tells me that Tusky's upstream code is not entirely free. What does that mean? Why isn't Tusky 100% FOSS? Is the app safe to use? Please do let me know.

Thanks.

**Comment by Vavassor** [comment]
It's still technically using Firebase Crash Reporting, which is a closed source library that connects to a google play service. But it's only in google play releases; the build for F-Droid doesn't include it at all.

It's not strictly needed, but it's been so good at finding errors. It could be replaced with a FOSS alternative like [ACRA](https://github.com/ACRA/acra), but I'd need to set up the server backend to collect reports and it'd take some doing.

**Comment by iknownothingaboutcomputers** [comment]
@Vavassor Then it's strange that the peeps at F-Droid still mention it as an anti-feature. Maybe you should contact them? As for the "it'd take some doing" part, well, privacy itself takes some doing. And google is bad news for privacy. Please switch to ACRA. Take your time. . . but do make the switch. Please.

Thanks for all your work. _/\_

**Comment by charlag** [comment]
@connyduck I think without push notifications the code is free? Or there's still some Firebase because of the crash reporting?

**Comment by connyduck** [comment]
The next Tusky release will be completly free. The current release uses firebase crash reporting, but I do not need it, Google Play Console is enough.

**Comment by connyduck** [comment]
I just removed all non-free dependencies from all build variants https://github.com/Vavassor/Tusky/commit/2859a5075ca9d8b583dd5374c18bedd7e1d4efd8
