### ISSUE TITLE
No longer on F-Droid

### ISSUE THREAD

**Issue by alexgleason** [Vavassor/Tusky#39]
The author [requested for this app to be removed](https://gitlab.com/fdroid/fdroiddata/issues/638) on F-Droid. Inclusion of non-free services prevents some users from installing the app. Personally, I don't even have Google Play installed on my phone at all. Hoping you will reconsider this, as everyone is willing to use free software but many people aren't willing to use nonfree software.

Thank you!

**Comment by df-unhuman** [comment]
I was just trying to do a local build to put it on my phone manually and ran into this issue. I also hope that you ether remove the necessity or make google play services optional. A big goal of Mastodon is to de-silo at least a part of our data, it would be useful if we didn't have to be forced into using Google's apis for its clients. 

Thanks and I hope you reconsider.

**Comment by DansLeRuSH** [comment]
Same thing for me, no Play Store on my phone and F-Droid is my only "market"

**Comment by r0bbie** [comment]
Just to add my disappointment at the reliance on Google Play Services, and thus the apps non-inclusion on F-Droid.

**Comment by regagain** [comment]
Same for me, no play services on my phone, only rely on F-Droid.

**Comment by SkyzohKey** [comment]
Please update the f-droid repo. 😉

**Comment by rugk** [comment]
Are Google Play Services the only non-free dependency this app has? If so, removing it in a floss built or so should be reliable.
Maybe the app needs an alternative push/pull system in that case, however. Other apps like Twidere have this, so maybe look how they do it.

**Comment by Jojonintendo** [comment]
I support this too! I no longer use Google Play Services and I would really appreciate if this app was on F-Droid :).

**Comment by matthiasbeyer** [comment]
Same here, please re-publish thisn on fdroid!

**Comment by halletienne** [comment]
Seems like it won't come back to f-droid as long as the dev is using firebase lib and services (proprietary). You can still get the apk from the website.

**Comment by mray** [comment]
A real bummer. I'd like to give it a try!

**Comment by GrimKriegor** [comment]
Aw, please do consider removing the non-free dependencies and allowing its distribution on F-Droid, even if on a separate server controlled by you.

**Comment by pierreduchemin** [comment]
As you may already know, Tusky uses firebase (the non-free dependency) to get push notifications from server when a toot is published.
The possible replacements for firebase are discussed here : https://github.com/Vavassor/Tusky/issues/84

A few days ago, I did create a free build of Tusky, but without notifications for now : 
https://unixcorn.xyz/web/statuses/67380
https://github.com/pierreduchemin/Tusky

**Comment by alexgleason** [comment]
[Riot](https://github.com/vector-im/riot-android) has a libre verson on F-Droid and one that uses Firebase on Google Play. I'm pretty sure it runs a server and polls, which does affect battery life on the F-Droid version. Still worth it to me, as I couldn't use it at all without this. Hoping OwnPush will be the sweeping solution that improves this for everybody, but their FAQ ("*Most* of the parts of that make up OwnPush will be made open source") does not inspire confidence.

**Comment by picsi** [comment]
@pierreduchemin Would you mind adding yours to F-Droid, at least until this bug is sorted out?

**Comment by mray** [comment]
I exclusively use F-Droid on LinageOS and those apks seem to work fine: https://tusky.keylesspalace.com/

**Comment by Vavassor** [comment]
[Tusky is on F-Droid](https://f-droid.org/repository/browse/?fdid=com.keylesspalace.tusky) again. It uses a polling notification system instead of the Firebase push notifications. I'd like this to be a temporary solution until Firebase can be wholly replaced, but I don't have a clear timeline on how long that will be.

There's a discussion to replace Firebase in issue #84 for anyone wants to continue that discussion there.

**Comment by Korb** [comment]
> [Tusky is on F-Droid](https://f-droid.org/repository/browse/?fdid=com.keylesspalace.tusky) again.

And even in two versions:

![Screenshot_2023_0305_213935](https://user-images.githubusercontent.com/3509797/222979614-630064fe-4ea3-4b21-ab85-dc22ecab26dc.png)

[Tusky (Tusky)](https://f-droid.org/packages/com.keylesspalace.tusky/)
![Screenshot_2023_0305_213958](https://user-images.githubusercontent.com/3509797/222979638-f152c0a5-b6d7-4d30-9706-e1dc86a088ae.jpg)

[Tusky (Unknown application)](https://f-droid.org/packages/com.keylesspalace.tusky.test/)
![Screenshot_20230305_214016](https://user-images.githubusercontent.com/3509797/222979645-dd2872af-2385-4479-816a-7c2d8910876d.jpg)
