### ISSUE TITLE
No CW button

### ISSUE THREAD

**Issue by allenerenee** [Vavassor/Tusky#392]
When posting from the app, the Content Warning button is not available. Some instances make heavy use of this feature as a courtesy.

**Comment by connyduck** [comment]
The feature is available on Tusky, but it is not a button but a checkbox hidden in the privacy settings of a toot. 
![screenshot_20170930-233256](https://user-images.githubusercontent.com/10157047/31049687-5ad2376a-a638-11e7-8713-628e93946955.png)

**Comment by charlag** [comment]
I think this should be closed too @connyduck
