### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by connyduck** [Vavassor/Tusky#394]
No commits to master and no releases since 2 month 🙁
I really like Tusky tough and it would be very sad if it dies like this

@Vavassor what is going on?
If you can not or do not want to support Tusky any longer, maybe you should transfer the project to another maintainer?

**Comment by charlag** [comment]
If things will turn out like I want them to I will be able to contribute properly in a month or so.

**Comment by connyduck** [comment]
Still no comment by @Vavassor on this :/
Honestly, by now I am thinking about forking Tusky and making my own release

**Comment by charlag** [comment]
@connyduck nothing really stops you. You can merge it back here I'd things get back on track.

**Comment by Vavassor** [comment]
Yeah, I've decided to step off this project. I made a post about it here: https://mastodon.social/@Vavassor/98817868240771813

I definitely would like to give it to another maintainer if I can. I could ask you @connyduck. So far, @kimmie@mastodon.social is the only other one who's expressed interest in picking it up.

**Comment by connyduck** [comment]
Thanks for the update. 
I want Tusky to get the new Android 8 and Mastodon 2 features - if nobody else wants to step in as maintainer, I would do it.

**Comment by charlag** [comment]
@Vavassor thanks for all the fish! You've done a great job here and I (and many others) are really grateful. Approach your dreams!

**Comment by charlag** [comment]
@connyduck @Vavassor I think no one else is ready - I would, but I can't yet.
So please, let's make a transition and release some updates!

I also would like to propose a policy that gives people write access if they have some merged pull requests. It is described [here](https://github.com/Moya/Moya/blob/master/Contributing.md) e.g. It is a great way to get some involved contributors.

**Comment by Vavassor** [comment]
@connyduck Alright, I think I'm prepared to hand things over to you! Do you have a preferred email or way for me to send you things like account details?

**Comment by connyduck** [comment]
I'll write you a private message on Mastodon

**Comment by charlag** [comment]
Please, close this issue?
