### ISSUE TITLE
Replies to boosted toot are inconsistent with the website

### ISSUE THREAD

**Issue by mkosler** [Vavassor/Tusky#40]
When I try and reply to a boosted toot, the only name that gets filled in as who I am replying to is the booster's account, not the original tooter's account. This is inconsistent with what happens in the main site, which fills in the name of the original tooter's account.

At the very least it should be consistent with the site, but I might as ask @Gargron to make it work like Twitter, where both the original tooter's​ and the booster's accounts are filled in when replying.

**Comment by Gargron** [comment]
It goes further than that, Tusky makes you reply to the *reblog* as opposed to the original toot. This could actually be cool behaviour, but needs to be accounted for on the Mastodon backend - who should that notify, how should such replies thread to the original, etc

**Comment by Vavassor** [comment]
Right now it's set to reply to the "actionable ID" so it is replying to the original post but filling in the mentions from the reblog. So it's goofy. I'm mending it!
