### ISSUE TITLE
reliable pull notifications

### ISSUE THREAD

**Issue by connyduck** [Vavassor/Tusky#401]
Unfortunately, pull notifications are quite unreliable. This is because newer Android versions limit the execution of background services.
Investigate the use of other methods to start services, like JobScheduler.

**Comment by connyduck** [comment]
We could use this library https://github.com/evernote/android-job/ to do the cumbersome handling of the different api versions. I tried it out, it works really well. Only drawback: It is not possible to schedule jobs in an interval shorter than 15 minutes (Android Oreo background execution limit).

**Comment by charlag** [comment]
@connyduck oh, I think that's what Mastalab is using... for everything, I guess. We could also check how Riot solves it https://github.com/vector-im/riot-android
