### ISSUE TITLE
Custom emoji too large

### ISSUE THREAD

**Issue by averageunicorn** [Vavassor/Tusky#404]
Sometimes they make the text a bit unreadable. (1.2 on Nougat)

![screenshot_20171022-105758](https://user-images.githubusercontent.com/10791840/31860311-6434a4a0-b718-11e7-9095-5bb926300b2c.png)
![screenshot_20171022-105823](https://user-images.githubusercontent.com/10791840/31860312-691e3828-b718-11e7-9b21-f0c07fe5de1e.png)

**Comment by koyuawsmbrtn** [comment]
I can confirm this 👍

**Comment by freundTech** [comment]
The bug isn't that emoji are to large, but that they aren't scaled at all. For me some are way to large and some are way to small.

![screenshot_20171022-143342](https://user-images.githubusercontent.com/9515067/31861959-3a0d8d2c-b736-11e7-932a-b87405eef647.png)

**Comment by connyduck** [comment]
fixed in #407
