### ISSUE TITLE
Network error while tooting

### ISSUE THREAD

**Issue by nailyk-fr** [Vavassor/Tusky#410]
Often, while tooting for GSM network a 'Network error' message pop up: 

![screenshot_20171024-120303](https://user-images.githubusercontent.com/16372405/31937375-80ed2bce-b8b4-11e7-90bf-e6bb0d86a77a.png)

How can I take logs? 
IMHO this happens while moving from WIFI to GSM, or if GSM connection had a drop. 
Killink app, restart it mostly solve the issue.

**Comment by charlag** [comment]
I noticed that it may happen not only because of the network but when you write a reply as well. It's probably some error with mention regexp and it keeps sending request for nickname autocompletion.

**Comment by connyduck** [comment]
fixed with https://github.com/Vavassor/Tusky/pull/414

**Comment by nailyk-fr** [comment]
Rebuilded app (including change) available on fdroid repo: https://releases.nailyk.fr/repo 
Thanks for the fix, will report ASAP.

**Comment by charlag** [comment]
@nailyk-fr I'm not sure I've fixed your particular issue, feel free to reopen if it's still occuring to you

**Comment by nailyk-fr** [comment]
Tested in known nonworking condition and it is perfect (rebuilt yesterday ~11h CEST, master branch)
Also app is more responsive and fast. 
Many thanks!
