### ISSUE TITLE
android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by connyduck** [Vavassor/Tusky#419]
There is an android.os.TransactionTooLargeException showing up in the PlayStore crash reports.
I suspect the problem is the onSaveInstanceState method of ComposeActivity. It writes whole bitmaps to parcels, very possible that the max transaction size gets exceded.

**Comment by charlag** [comment]
@connyduck as far as I understand, previews are saved for the case of configuration change. The code itself is pretty confusing. It would be nice to have ViewModel or something else that survives rotation so we don't have to save as much (only already uploaded photos, we can get previews by URLs). It could simplify things significantly, but it's a pretty big change (and possibly new dependency). I am not sure I have time to rewrite this screen so much now.
I think if we want quick-and-dirty solution we can just fetch previews again on restore, I think I can try that.

**Comment by charlag** [comment]
@connyduck a-ha! I've sound another but with this (#380). There's no check for queued media status, so even if it already was uploaded - it will be uploaded again.

**Comment by connyduck** [comment]
Yes it absolutely makes sense to have previews surviving config changes, but I think they are responsible for this crash. I am not sure though, I could not reproduce it. It is one of the bigger crashes I see in the crash reports, affects quite some users.

**Comment by charlag** [comment]
@connyduck I've tried re-making thumbnail and looks like it's fast enough to not be a problem even when there are multiple of them. It probably shouldn't be done on the main thread but it works fine. I'll submit it and you can tell me if it's okay. Without Rx I'm missing an easy way to do things in the background (AsyncTask is meh and writing our own thread pools seems.. questionable. Coroutines maybe?)

**Comment by connyduck** [comment]
thx for the fix, I will keep an eye on the crash reports to see if this really was the problem
