### ISSUE TITLE
"Follow" FAB doesn't change after following user

### ISSUE THREAD

**Issue by nevillepark** [Vavassor/Tusky#42]
When viewing a user's profile, the FAB looks the same both before and after following. The "+" should be changed to an "x" or something. Maybe a colour change too? 

![_20170331_200804](https://cloud.githubusercontent.com/assets/16054979/24573484/86c2968e-1651-11e7-99c6-6e8c4d6838b6.JPG)
![_20170331_200823](https://cloud.githubusercontent.com/assets/16054979/24573485/86c48160-1651-11e7-954b-96982eb7f2df.JPG)

**Comment by Skirmisher** [comment]
Currently, the button will disappear after following, but only after you leave and re-enter the profile page. I agree there should be some immediate feedback, though I'm not sure turning it into an unfollow button is a good idea (I'd imagine follows happen more often than unfollows).

**Comment by ryanleesipes** [comment]
Either way it needs to change, disappear, or do something (I think an unfollow would be good, otherwise I'd be confused about where to do so and I think most users would expect to be able to unfollow where they followed). But right now, until coming here, I just figured that feature was broken.

**Comment by theZacAttacks** [comment]
It was fixed in a recent merge, but I'll put in another pull for having it change the icon and allow you to unfollow/follow from the same fab.

**Comment by ryanleesipes** [comment]
Thank you @theZacAttacks

**Comment by Vavassor** [comment]
This was closed as of 3a0fc9d3db1dd032235e7220bc4410e06fb94a12
