### ISSUE TITLE
App crashing when switching between portrait and landscape mode in profile view [Tusky v1.0.3]

### ISSUE THREAD

**Issue by koyuawsmbrtn** [Vavassor/Tusky#43]
When I turn around my phone from portrait to landscape, the app instantly crashes on the profile view. I don't know if it's a device specific issue, but I guess some people might have this problem as well.

**Comment by israuor** [comment]
+1

Same here on oneplus two running lineage OS (Android 7.1.1)

**Comment by BanjoFox** [comment]
I am seeing this issue on my Nexus 5x (Android 7.1.1) with version 1.10. 
It is pretty frequent (9 out of 10 times). Would you like a new issue opened?

**Comment by Vavassor** [comment]
The crash when composing is a separate bug, which I also fixed yesterday. I just haven't pushed the updated version to google play yet.

**Comment by BanjoFox** [comment]
I am glad I asked first then ;)
Thanks for letting me know!
