### ISSUE TITLE
Search function for hashtags

### ISSUE THREAD

**Issue by israuor** [Vavassor/Tusky#44]
Can tap on hashtags in toots (posts) in my Timeline, but cannot specifically search for any hashtags, just for users? As workaround I can write a new post with the hashtag I'd like to search for in it. But it's kinda.....

**Comment by snaggen** [comment]
This is the biggest issue I have with Tusky right now. Hashtag search is something I use quite often to find interesting posts and new people to follow.

**Comment by israuor** [comment]
There's a workaround. Toot something with a hashtag in it. Tap on the hashtag afterwards. ;)

**Comment by Vavassor** [comment]
I've added this at the same time as work on Issue #67. Moved search to its own page and now hashtags and accounts can be searched. Also, it responds to native intents for searches (android's native search functionality).
