### ISSUE TITLE
No notification authorisation

### ISSUE THREAD

**Issue by Zirconiumirish** [Vavassor/Tusky#444]
Hi is it normal that there is no authorization popup ?

Thanks

**Comment by connyduck** [comment]
What exactly do you mean by "authorization popup"?

**Comment by Zirconiumirish** [comment]
The notifications are on in the app but you know you should have an authorization popup from android to accept to be notified.

**Comment by charlag** [comment]
@Zirconiumirish Android apps don't require user permission to send notifications?

**Comment by Zirconiumirish** [comment]
Okay sorry i though I have already seen a popup asking for that lol My mistake

Thanks

Another question is is it possible to port this on ios ?

**Comment by charlag** [comment]
No, sorry, there are a lot of other high-quality Masto apps for iOS:
https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/Apps.md
