### ISSUE TITLE
Boosting or favouriting a status with a link preview card makes the card disappear

### ISSUE THREAD

**Issue by connyduck** [Vavassor/Tusky#446]

**Comment by charlag** [comment]
This problem is broader than it seems, it requires the same ```ViewData``` machinery as in other fragments because of the WCs

**Comment by MasterGroosha** [comment]
Same bug with "spoiler"
F.ex. https://mastodon.social/@charlag/98999142367445875

**Comment by connyduck** [comment]
fixed https://github.com/Vavassor/Tusky/pull/445
