### ISSUE TITLE
Support TLS 1.1 and 1.2 for old android versions

### ISSUE THREAD

**Issue by Technowix** [Vavassor/Tusky#448]
Rightnow, I'm keeping TLSv1.0 on my instance since there isn't any mobile client that support TLSv1.1 nor 1.2 on android 4.1 to 4.3 (fixed in 4.4)
It doesn't seem to be that hard for Tusky to support TLS 1.1/1.2 on thoses android versions, but I can be wrong : 
https://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/

**Comment by charlag** [comment]
Oh, sorry, we'be tried to ship our own TLS and it didn't end well https://github.com/Vavassor/Tusky/issues/46
I feel you but I'm not sure about this.

**Comment by Technowix** [comment]
There is no need to ship custom TLS as you can read, simply to force android to give the access :)

**Comment by charlag** [comment]
@Technowix ah, sorry, I didn't pay enough attention. Cool then, worth trying, I guess. Thank you.

**Comment by connyduck** [comment]
Yes, we should give this a try. But we need to be careful to not change the Tls fix for Nougat we already have in place.

**Comment by Vavassor** [comment]
This should already be implemented in [OkHttpUtils.java](https://github.com/Vavassor/Tusky/blob/a58ac243a395e13e0fb286e08d6f0dfd388cfc56/app/src/main/java/com/keylesspalace/tusky/util/OkHttpUtils.java#L155). The class SSLSocketFactoryCompat at the bottom, is pretty much the example linked, right?

**Comment by connyduck** [comment]
Yes indeed, thx for the hint @Vavassor.
Do we know a instance with TLS 1.2 only so we can test it?

**Comment by Technowix** [comment]
Just tried with someone having 4.2 and, no, not working :v 
mstdn.io have only TLSv1.2

**Comment by connyduck** [comment]
Sorry, but we will not put in any more time to investigate Android 4 issues. See https://github.com/Vavassor/Tusky/issues/476
