### ISSUE TITLE
Improve default toot privacy setting to more closely match web mastodon

### ISSUE THREAD

**Issue by connyduck** [Vavassor/Tusky#461]
see this toot & the replies
https://mastodon.social/@Tusky/99043921356149215

When replying, Tusky should always inherit the privacy setting.

For non-replies we should add a setting in the preferences (or use the setting of the last non-reply toot)

**Comment by Vavassor** [comment]
Yeah, I caught a couple more folks being confused by this. https://mastodon.social/@maloki/99042704677804378 Maybe it would be good to match the web client.

**Comment by KonomiKitten** [comment]
I agree with matching the web client I didn't realise I was doing so many public tweets on Tusky at first.

**Comment by connyduck** [comment]
Fixed https://github.com/Vavassor/Tusky/commit/1c2a647569d29440c2b09d0d41aeddd6c67632bc
