### ISSUE TITLE
App can't authenticate on (new) server

### ISSUE THREAD

**Issue by YoungLink4** [Vavassor/Tusky#462]
Downloaded the app from the appstore to use it on a very fresh mastodon server. Unfortunately the app can't authenticate itself on the server. Server admin has no issues and I can use Tusky just fine on mastodon.social for example

**Comment by connyduck** [comment]
What Android version and device are you using, what is the server in question and do you get any error messages? Thx!

**Comment by YoungLink4** [comment]
Android version: 4.4.2
Device: Samsung Galaxy S3 Neo
Error message is "App can't authenticate on the server". The same I get when I put in gibberish
Server: anitwitter.moe (currently down) but I have the same problem on toot.love. Works fine for niu.moe and friends.nico

**Comment by connyduck** [comment]
Ok this is the same issue as https://github.com/Vavassor/Tusky/issues/448
friends.nico supports TLS 1, 1.1, 1.2
toot.love only 1.2
