### ISSUE TITLE
theme changes from dark to light, while creating a toot, and switching from portrait to landscape

### ISSUE THREAD

**Issue by govvin** [Vavassor/Tusky#467]
I'm using the dark theme, but when creating a toot, and I switch to landscape, the screen changes to a light theme. I'm uisng 1.3.1 on Android Oreo

![image](https://user-images.githubusercontent.com/5821688/33228247-6ca93468-d1f1-11e7-9180-4e4a67918d1b.png)

![image](https://user-images.githubusercontent.com/5821688/33228248-77854106-d1f1-11e7-9d8e-d8e3182bd1da.png)

**Comment by connyduck** [comment]
Well, this is not the light theme, this is just how your phone displays the extended TextView. Just minimize the keyboard and you will see what I mean.
