### ISSUE TITLE
French flag not displayed, C P is displayed instead

### ISSUE THREAD

**Issue by clement-analogue** [Vavassor/Tusky#473]
The French flag is not displayed in Tusky, `C P` is displayed instead, whereas the others that we tried work fine.

![4b7cb445657b5332](https://user-images.githubusercontent.com/1931507/33476494-7e364bea-d682-11e7-9831-39f297634cf0.jpg)

Version 1.3.1
Instance: toot.forumanalogue.fr

**Comment by connyduck** [comment]
What Android version are you using? Can you give me a link to that toot? Does the french flag show correctly in other apps?

**Comment by clement-analogue** [comment]
Android v6.0.1
It is working with the web browser on the same phone. Is it enough or shall we install another Mastodon app to perform further tests?
This happens for example on this profile:
https://toot.forumanalogue.fr/web/accounts/217

**Comment by connyduck** [comment]
Seems like you are using the emoji for Clipperton Island and not the one for France.
https://emojipedia.org/flag-for-clipperton-island/

**Comment by clement-analogue** [comment]
In Mastodon, it is `:flag-fr:` So it is an error in Mastodon where they use Clipperton Island's flag for the French one?

**Comment by connyduck** [comment]
Well the emoji in question definitely is the Clipperton Island one. And it is not supported in Android 6, so it renders as CP. I have no idea how it ended up in the profile though. You could try copy pasting the correct french emoji from emojipedia, that should fix the issue. https://emojipedia.org/flag-for-france/
