### ISSUE TITLE
Wrong mobile notification content

### ISSUE THREAD

**Issue by emanchado** [Vavassor/Tusky#48]
When a mobile notification comes for *several* Mastodon notifications, Tusky seems to show the avatar associated with the user in the oldest Mastodon notification, but the text of the newest.

For example: if @aaa sends me a "hi!", and then @bbb sends me "Hello there!", the Tusky mobile notification will show @aaa's avatar with the text "Hello there!".

Small clarification: I usually have internet off on the phone, that's why it's pretty common for me to receive several Mastodon notifications in the same Tusky mobile notification. You might need to do that in order to reproduce the bug.

**Comment by daycode** [comment]
Now it's fixed, can you close this issue ?
