### ISSUE TITLE
New arabic translations to merge

### ISSUE THREAD

**Issue by BoFFire** [Vavassor/Tusky#487]
Hello,
Please find new arabic strings pulled from my Transifex : 
https://cloud.indie.host/s/9324mSnquV3QI5u

Best regards,

**Comment by connyduck** [comment]
Thank you, I updated the translations https://github.com/Vavassor/Tusky/commit/73342d38cf3bcb41cdef4e05f5c50e05d0005e5d ☺️
 
Please send a pull request next time you improve the translation
