### ISSUE TITLE
Option to disable website content prefetch

### ISSUE THREAD

**Issue by Dostoi** [Vavassor/Tusky#496]
Hi :)

Is it possible to have an option to disable website content fetching ?
Fetching some toot ins't an issue, but doing so for some website is concerning for privacy in an era of mass surveillance and I'd rather access them from Tor.

I'm talking about the square with the picture and text that it automatically added (so not showing it but more importantly not fetching the content in the first place).
![screenshot_2017-12-30-09-21-49](https://user-images.githubusercontent.com/7694864/34452608-2215c89a-ed43-11e7-8851-2e1d50817009.png)

Thanks for the app!

**Comment by connyduck** [comment]
The content is not fetched by Tusky, but by your mastodon instance. It fetches the content once when the link is posted and then caches it. So Tusky showing the preview has no privacy implications and we do not think a option to disable the preview is necessary. 🙂

**Comment by Dostoi** [comment]
Oh great then ! :)
I though it was done on the client side but it's better this way.
Thanks for the feedback
