### ISSUE TITLE
[BUG] About Tab

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [Vavassor/Tusky#519]
If I deselect the 'Show Boosts' and 'Show Replies' options under Tab, then they work only as long as I'm using the app. Once I exit, they revert to their default state. This shouldn't happen.

**Comment by connyduck** [comment]
Thx for reporting!
Fixed in https://github.com/Vavassor/Tusky/commit/5dbe3c927e6e7dd49ceaa6087f0195592bf0a024.
Will be released with the next update.
