### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by coolacid** [Vavassor/Tusky#54]
Would be nice to have the ability to have multiple instances running, this will probably be a thing sooner rather than later.

**Comment by alex73630** [comment]
A multiple account option like the Twitter mobile app would be awesome !

**Comment by Vavassor** [comment]
This is definitely planned! A lot of folks have been asking for it on Mastodon itself, and a lot of folks have been getting more accounts with the recent proliferation of instances.

**Comment by steve31266** [comment]
Related request: ability to browse the details of other instances, perhaps by clicking on someone's profile, or by entering an instance address, or scrolling through a list of instances.

**Comment by zet4** [comment]
It's been few months since this issue was made, has there been any progress?

**Comment by connyduck** [comment]
There has not been any progress, but multi account support is one of my personal priorities for Tusky.

**Comment by connyduck** [comment]
Lets prioritize this since I am getting so many requests for multiple account support.

**Comment by charlag** [comment]
Okay, so we need to separate SharedPreferences?
I think we should inject them somehow instead of just requesting them everywhere. Then we can provide screens with the ones they need.
I'm not sure if we should separate drafts between accounts.
Also notifications will need some work.
I think we may have separate preferences (like Settings) for each account, it shouldn't be too bad.

**Comment by connyduck** [comment]
I would switch from SharedPreferences to a database table that stores logins. There can always only be one active login. You only get notifications for that one active login. (we can improve that later)

**Comment by wakingrufus** [comment]
Nice to have: when retooting, prompt for which account to retoot from

**Comment by charlag** [comment]
It would be harder but it would be more correct.
I don't see a problem with fetching notifications for multiple accounts.
I've checked and it seems that preferences are not used too much so migration to DB wouldn't be too painful.
I would make a CurrentUser class which has methods to fetch cached current info.

**Comment by charlag** [comment]
@wakingrufus it is a good idea but it would be a little hard to do so it probably should be done later.

**Comment by connyduck** [comment]
finally done :) #490
