### ISSUE TITLE
Replies to toots look like a single long thread when the parent toot is selected

### ISSUE THREAD

**Issue by mkosler** [Vavassor/Tusky#57]
When I select a toot that has received replies from multiple different users, it looks as though all the replies are [threaded together.](https://cloud.githubusercontent.com/assets/1159095/24705994/b5e3c2c8-19d3-11e7-8d8d-8f4fbabcf5c4.png)

When I select the actual reply toots, you can see that [they are not.](https://cloud.githubusercontent.com/assets/1159095/24706035/eb82d400-19d3-11e7-80b3-fd87816e6ada.png)

**Comment by Vavassor** [comment]
(This isn't quite a bug, but it's certainly cause for undue confusion, so I'm treating it like one.)

**Comment by charlag** [comment]
Awesome, so great that it's finally closed!
