### ISSUE TITLE
Push notifications with federated instances

### ISSUE THREAD

**Issue by mcg** [Vavassor/Tusky#58]
App Version: 1.1.0
Android Version: 7.1.2

Push notifications haven't ever been very reliable for me, but since moving to my own Mastodon instance, I wanted to confirm that I should still get push notifications from my instance? Also, any idea why pushes are so unreliable?

**Comment by Vavassor** [comment]
There's a dedicated server for tusky's push notifications, but it's rather unstable right now. I need to replace some of its code, but I've been focusing on crashes with the main app and people who can't log in and things first.

You should be able to get push notifications from any instance when it's working properly, though.

**Comment by mcg** [comment]
Good to here. Thank you for the awesome client!
