### ISSUE TITLE
f-droid repo out of date

### ISSUE THREAD

**Issue by tchncs** [Vavassor/Tusky#6]
Hi there, please update the f-droid repo.
There are at least a few people using your client already.

> Version 1.0.0-alpha.5 - Added on 2017-02-24

**Comment by KonomiKitten** [comment]
Looking at the F-Droid repo page for Tusky it's now at **Version 1.0.0-alpha.8 - Added on 2017-03-10** so I presume this should be closed?

**Comment by tchncs** [comment]
Yes, i think so.

**Comment by haverholm** [comment]
Just continuing here instead of starting a new issue; it seems now Tusky isn't to be found at all on F-Droid. Did the increased interest in Mastodon overwhelm their servers, or any other reason for this?

**Comment by daycode** [comment]
@haverholm  whatch here https://gitlab.com/fdroid/fdroiddata/issues/638

**Comment by haverholm** [comment]
Ah! Well, if they're using closed-source parts it's not for me anyway.
Thanks for a quick reply!

**Comment by daycode** [comment]
But it could be interesting to know why @Vavassor made the choice to use Firebase 🤔 because I'm installing dev environment and didn't really want to sign in to it 😞

**Comment by Vavassor** [comment]
@daycode It was mostly @Gargron that implemented push notifications. It's a must-have feature for me and Firebase seemed like the most expedient way to accomplish it. So we agreed on its use even though it meant leaving F-Droid. I always figured if a suitable replacement was found, or if I was able to make one, it could be put back on F-Droid.

I didn't think about how it was required for contributors, though. I need to make it optional for building, then. It's only used for push notifications (and crash reports), so for most work it's unnecessary.

**Comment by KonomiKitten** [comment]
@Vavassor although I closed the thread about not getting push notifications I believe that I am definitely not getting notifications 99% of the time lately, so I wonder how worth it this Firebase part of Tusky is worth it, it doesn't seem to work very well anyway...

**Comment by Vavassor** [comment]
@KonomiKitten I don't think it's firebase's part of the equation that's broken, there. It's using https://github.com/Gargron/tusky-api, and it has at least one major bug causing connections to enter a retry-reconnect loop. Also, it's affected by the TLS settings bugs #46 that I'm working on for the login page, so some users can't connect to it to receive notifications at all.

But yes, they're mostly broken right now. I'm not super confident in repairing/improving the current server so I'm trying to weigh whether that will take more effort than making a new one. It's code that's pretty outside my wheelhouse. I know I can do it, but I'm worried it will take a long time.

**Comment by KonomiKitten** [comment]
@Vavassor that explains why they are so off and on for me, I thought I was going nuts
