### ISSUE TITLE
Notification tab spins indefinitely 

### ISSUE THREAD

**Issue by exadeci** [Vavassor/Tusky#62]
It seems that if you never received a notification the tab loading will spin indefinitely, not a big issue but it'll happen to all new users.

**Comment by raphaelm** [comment]
This does not only apply to the notifications, but to all tabs. I'm working on a simple solution.

**Comment by daycode** [comment]
now the commit is merged, could you close this issue ? 😉

**Comment by connyduck** [comment]
This still happens on the "Blocked Users" and "Muted Users" page.

**Comment by Vavassor** [comment]
I fixed it to not occur on account lists like blocked and muted users back in commit 275cd51a6db2a1f119ff01e3091603fda32860db. It should be the same in all lists and timelines, now.
