### ISSUE TITLE
Simplify header of main app screen

### ISSUE THREAD

**Issue by alerque** [Vavassor/Tusky#67]
The current header takes up two lines, one for the menu and one for tabs.

![Tusky header](https://cloud.githubusercontent.com/assets/173595/24751663/27d68186-1ad3-11e7-9f5e-d6ca64e39d54.png)

While this isn't bad looking, I think it takes up more space than it needs to. First of all the search really isn't that useful. Since it's only a username lookup function and used relatively infrequently, I think it could be relegated to a main menu item or a tab of it's own. This would easily allow the tab bar to  move up  into the first row of the header.

A good example of this  one line approach for a similar scenario is [Twittnuker](http://twittnuker.org/)'s main screen:

![Twittnuker header](https://cloud.githubusercontent.com/assets/173595/24751666/2b8027d8-1ad3-11e7-8cb1-a2c801b69f0d.png)

I think Tusky could benefit from this slimmer UI approach. Search could be an item under the main app menu.

**Comment by Vavassor** [comment]
I was considering something like that. Could try something like that without the text labels for the tabs. I was already having trouble with long words like "Notifications" and "Federated" on screens that weren't very wide.

The search needs to be revised a bit anyway so it can search tags, and it never needed prominent placing like that.

**Comment by daycode** [comment]
It could be interesting ot use native Search Interface in replacement of the library Floatingsearchview.
