### ISSUE TITLE
Open profile in Tusky when clicking @username links

### ISSUE THREAD

**Issue by jeepfromoil** [Vavassor/Tusky#70]
Clicking a hyperlinked @username in a toot opens the profile page in the Web browser instead of in Tusky (when the user is in a remote instance).

For some reasons, clicking the avatar of the same user opens the profile in the app (as expected).

This behavior isn't consistent and it makes it very difficult to follow remote users.

**Comment by SkyzohKey** [comment]
:+1:

**Comment by Vavassor** [comment]
The implementation definitely treats it like a hyperlink, with the source set to the [url for their Account object](https://github.com/tootsuite/mastodon/blob/master/docs/Using-the-API/API.md#account). I should change it, though for sure.

**Comment by Vavassor** [comment]
I forgot to tag this issue, it was fixed in commit b6e72a94be90ae7bffddf4ce06ea135130118871.

**Comment by remi6397** [comment]
This issue hasn't been fully fixed yet.

When I click link to @ConnyDuck's on @Tusky's official profile, it just opens in browser/custom tab, depending on preference.
