### ISSUE TITLE
Clicking the avatar in drawer menu doesn't open the profile.

### ISSUE THREAD

**Issue by SkyzohKey** [Vavassor/Tusky#78]

**Comment by daycode** [comment]
Are you sure (or it was fix) ? because this is I have

![clck-drawer-profile](https://cloud.githubusercontent.com/assets/13915512/25305370/56dacc4a-277a-11e7-90f0-694e32af161c.gif)

**Comment by SkyzohKey** [comment]
The issue is old and the latest release fixed that i guess, thus closing.
