### ISSUE TITLE
Display boosts and favourites for toots

### ISSUE THREAD

**Issue by kjhoerr** [Vavassor/Tusky#79]
In the web UI you can expand toots to see the number of boosts and favourites the toot received. There is no way to view this in Tusky.

**Comment by Vavassor** [comment]
I actually don't like seeing boost and favourite counts, so that's partially why I've been avoiding it. I've heard others informally mention on mastodon that they wanted this, though.

I was planning on modifying the thread view anyways with a larger-font detail view for the selected toot, to make it clear which one is the selected post and which are the replies. So I think what I'd like is to show the numbers of boosts/favourites there. And then add a preference to show/hide the counts.

**Comment by SkyzohKey** [comment]
:+1: for displaying this, that's an useful information, ie. to avoid opening a thread if it hasn't any reply

**Comment by kjhoerr** [comment]
I think that's the best way to do it, especially since that's the way the web UI handles it. Consistency is always good.

**Comment by Pangoraw** [comment]
I am currently experimenting with this. You are right, in this thread there should **primary** and **secondary** toots. And the counts should only be shown for the **primary** toot.

As for how to show them, I am thinking about two ways :

1. By using only icons : 

![Preview](https://mastodon.xyz/system/media_attachments/files/000/229/582/original/e7b0b95d0b438b77.jpg?1494963808)

2. By using text (I am less fond of it) :

![Preview2](https://mastodon.xyz/system/media_attachments/files/000/229/583/original/d97692dd78a748c9.png?1494963813)

Let me know which solution you prefer.

**Comment by Vavassor** [comment]
I was thinking of just doing it like twitter apps usually do it, where the count is next to the button and it shortens long numbers like "2k" for "2000".

But, if you want to do it this way, I think the icons look better. Although, they should be a different colour from the buttons below them, so no one expects to press them. Possibly just match the lighter colour the counts are using?

**Comment by Pangoraw** [comment]
Such counts will only be shown on the `ViewThreadActivity`, and then I can add non-clickable counts on the sides of the icons for statuses shown on the main timelines.

**Comment by connyduck** [comment]
In the next Tusky release there will be a detailed status view where you can see the number of boosts and favourites.

**Comment by Tak** [comment]
They're in the detailed view for each post. They're intentionally not displayed in the timelines.
