### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by Gargron** [Vavassor/Tusky#9]
- [ ] Add Firebase libraries to the Android project
- [ ] Upon first login, send device token, instance URL and access token to app's own server
- [ ] Upon logout, send device token to the app's own server for de-registration
- [ ] Node.js server that accepts device token registrations/deregistrations\*, connects to streaming APIs of mastodon servers

\* Method of authentication for the app server? Simple but long API key? Should requests be signed with an API secret?

**Comment by psydwannabe** [comment]
Since this is currently the first result on Google for searches involving Tusky and push notifications, I thought it might be helpful to note that as of this writing, a solution for them is in progress as noted in greater detail in issue #84.
