### ISSUE TITLE
Replies/Threads don't show when clicking on a boosted toot

### ISSUE THREAD

**Issue by cnovel** [Vavassor/Tusky#91]
When clicking on a boosted toot, previous/next replies don't show up. Here's a comparison between the web view and Tusky view.
![webthread](https://cloud.githubusercontent.com/assets/5690282/24795373/6ceba696-1b89-11e7-9b36-b0da34bc197f.PNG)
![tuskythread](https://cloud.githubusercontent.com/assets/5690282/24795376/6f257284-1b89-11e7-8d76-f4a6eb58690f.png)

**Comment by Vavassor** [comment]
Oh wow, this is silly mistake. Boosts/reblogs are their own object separate from the post being boosted, both in Tusky and the Mastodon API. So I'm pretty sure this error is just because I give the status view page this weird object instead of the original post.
