### ISSUE TITLE
Can't paste text in search field

### ISSUE THREAD

**Issue by Fortyseven** [Vavassor/Tusky#94]
Turns out this already has a [ticket](https://github.com/arimorty/floatingsearchview/issues/173) filed over on the [floatingsearchview](https://github.com/arimorty/floatingsearchview) project. It has a fix incoming, apparently. 

Just creating **this** ticket so it's kept track of. :)

**Comment by arimorty** [comment]
Hey @Fortyseven Just pushed version 2.0.4 of the library (that contains a fix for this issue) to Maven. It should be available on Maven within hours.

Thanks for introducing me to mastodon 😉

**Comment by Vavassor** [comment]
I updated FloatingSearchView to the new version in commit 41088de6be67b064cf27921c940f9fddde73421d so this was fixed in the Tusky 1.1.3 release.
