### ISSUE TITLE
Better launch icon

### ISSUE THREAD

**Issue by daycode** [Vavassor/Tusky#95]
Here an icon I made for you app, feel free to use it if you want it or If you agree to use it, I can made a pull request with icon replacement. ( I can't send the svg from here :/ )

## icon updated, take this one.
![tusky-logo](https://cloud.githubusercontent.com/assets/13915512/24835964/0a66914c-1d10-11e7-8c4c-be9fa15806ac.png)

**Comment by connyduck** [comment]
I like this one, but I think it should have a slight shadow like the official google icons have.

**Comment by daycode** [comment]
And like that, is it better for you ? 

![tusky-logo](https://cloud.githubusercontent.com/assets/13915512/24820360/e7b3a52c-1be8-11e7-95a6-29813ac7bc7e.png)

**Comment by connyduck** [comment]
I meant something like that

![tusky](https://cloud.githubusercontent.com/assets/10157047/24821904/a6a27460-1bf1-11e7-8dc8-4d643bb64eea.png)

check out the official google app icon: https://www.apkmirror.com/apk/google-inc/google-search/google-search-6-16-31-release/

**Comment by daycode** [comment]
I made few modifications and add the shadow like you said. Is that ok know ? 

![tusky-logo](https://cloud.githubusercontent.com/assets/13915512/24826766/bc6c0be8-1c3d-11e7-94c0-d2b5dc569366.png)

**Comment by SkyzohKey** [comment]
Like that icon, looks so smooth !

**Comment by connyduck** [comment]
really awesome 😍

**Comment by Vavassor** [comment]
@daycode I do like this one! Mine I maybe did a bit too much with the gradients/lighting. I've noticed it doesn't fit so well alongside a lot of android icons. So a cleaner one like this is nice.

**Comment by Gargron** [comment]
I like @Vavassor's icon tbh.

**Comment by daycode** [comment]
@Gargron what did you like about them that isn't in the new one ? for me, there was a too big difference of design between the launch icon and the splashscreen, the splashscreen is flat but the launch icon have a gradiant and this 2 icons are one between the other 😕

**Comment by daycode** [comment]
So @Vavassor , what is the final decision about the icon ? 🤔
