### ISSUE TITLE
Switch to GPL

### ISSUE THREAD

**Issue by alerque** [Vavassor/Tusky#96]
This is a full blown app not a library. There really isn't much of a use case for it embeded inside another app, so the LGPL is not really helping anybody and it is hindering the project.

It's not too late to switch. There are a limited number of contributors to date, just check with them and make sure they are okay with re-licensing. If so, change the license. All past work would be dual licensed, all future work would be GPL only, with of course the LPGL clauses for libraries that it includes.

**Comment by Vavassor** [comment]
Alright, I'm DM-ing the other contributors on mastodon right now about the possible change.

**Comment by Vavassor** [comment]
I finally got word back from all the contributors, so I'm going to make the switch on the master branch.

**Comment by Vavassor** [comment]
It is changed to GPL3 as of 4d9fd09a3c39e73afd377ff9c0b1c53219af5e2e
