### ISSUE TITLE
elephant_friend.png has too low resolution

### ISSUE THREAD

**Issue by connyduck** [Vavassor/Tusky#99]
It looks really blurry on my xhdpi and xxhdpi devices.
I tried to find the image in a higher resolution to no avail.

So I think we should use another image, maybe this one? https://commons.wikimedia.org/wiki/File:Mastodon_Social_Logo.png

**Comment by daycode** [comment]
the current image is from mastodon, and it haven't svg or bigger size ( [link here](https://github.com/tootsuite/mastodon/blob/master/app/assets/images/mastodon-not-found.png) ), I can open an issue on mastodon to have a bigger one or the source file and integrate it here with a PR.

**Comment by elioqoshi** [comment]
Just recreated it. Here is the PNG

![png](https://cloud.githubusercontent.com/assets/5436686/24839573/785214b8-1d5d-11e7-8ed7-3fe874b9e765.png)

And the SVG:
https://cloud.ura.design/s/2ke9Wrcg3bK7qgA

It's not perfectly the same, but the best I can do from manually tracing it.

**Comment by daycode** [comment]
It's ok for me, I'm going to do the PR 😃

**Comment by elioqoshi** [comment]
@daycode Sure! However it's a derivative work from the original image, I'd assume. I'm fine with CC-BY-SA 4.0 International

**Comment by elioqoshi** [comment]
@daycode I forgot a small detail, let me update it!

**Comment by elioqoshi** [comment]
![png](https://cloud.githubusercontent.com/assets/5436686/24840109/56dd8100-1d67-11e7-811e-bc973ea90094.png)

SVG: https://cloud.ura.design/s/2ke9Wrcg3bK7qgA

There, good to go

**Comment by daycode** [comment]
nice you added Trumpet strokes 😃

**Comment by alerque** [comment]
@elioqoshi You should probably mention this and maybe contribute it upstream too! See [this issue](https://github.com/tootsuite/mastodon/issues/1245).

**Comment by elioqoshi** [comment]
@alerque Thanks!

**Comment by connyduck** [comment]
So, any update on this? We could also you the fluffy elephant friend I guess? It is available in higher resolution. 

![elephant_friend](https://assets.mastodon.social/assets/fluffy-elephant-friend-6b47d8e924332955795ff4b2d8fc446437d26b28bfc67d6be2a4d88995ab2c1f.png)

**Comment by Vavassor** [comment]
Sorry, I lost track of this issue. Android recommends not to have large vector images on screen so I just rendered @elioqoshi 's .svg to a higher resolution .png.

**Comment by connyduck** [comment]
Oh, very nice. I would recommend providing it in different resolutions for mdpi, hdpi, xhdpi and xxhdpi screen densities though.
